<?php
	$dbServer = 'tm.premjees.in';
	$dbUsername = 'vvidin_tm_premjees';
	$dbPassword = 'Another10$1';
	$dbDatabase = 'vvidin_tm_premjees';
	$dbPort = '3306';
	$appURI = 'task_master';
	$host = 'localhost';

	$adminConfig = [
		'adminUsername' => "tm_premjees",
		'adminPassword' => "\$2y\$10\$U/LiQ2GbU1lBBcM2p6NcyOXt22EJ5tLsWa3LRaS8M2evbMK3ee2mq",
		'senderEmail' => "archanasharma2001828@gmail.com",
		'notifyAdminNewMembers' => "",
		'defaultSignUp' => "1",
		'anonymousGroup' => "anonymous",
		'anonymousMember' => "guest",
		'groupsPerPage' => "10",
		'membersPerPage' => "10",
		'recordsPerPage' => "10",
		'custom1' => "Full Name",
		'custom2' => "Address",
		'custom3' => "City",
		'custom4' => "State",
		'MySQLDateFormat' => "%d/%m/%Y",
		'PHPDateFormat' => "j/n/Y",
		'PHPDateTimeFormat' => "d/m/Y, h:i a",
		'senderName' => "Membership management",
		'approvalSubject' => "Your membership is now approved",
		'approvalMessage' => "Dear member,\n\nYour membership is now approved by the admin. You can log in to your account here:\nhttp://localhost/task_master\n\nRegards,\nAdmin",
		'hide_twitter_feed' => "",
		'maintenance_mode_message' => "<b>Our website is currently down for maintenance</b><br>\r\nWe expect to be back in a couple hours. Thanks for your patience.",
		'mail_function' => "mail",
		'smtp_server' => "",
		'smtp_encryption' => "",
		'smtp_port' => "25",
		'smtp_user' => "",
		'smtp_pass' => "",
		'googleAPIKey' => "",
		'baseUploadPath' => "images",
	];