<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/howrs.php');
	include_once(__DIR__ . '/howrs_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('howrs');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'howrs';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`howrs`.`howrs_id`" => "howrs_id",
		"`howrs`.`howrs_howr1`" => "howrs_howr1",
		"`howrs`.`howrs_howr2`" => "howrs_howr2",
		"`howrs`.`howrs_howr3`" => "howrs_howr3",
		"`howrs`.`howrs_description`" => "howrs_description",
		"`howrs`.`howrs_created`" => "howrs_created",
		"`howrs`.`howrs_updated`" => "howrs_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`howrs`.`howrs_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`howrs`.`howrs_created`',
		7 => '`howrs`.`howrs_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`howrs`.`howrs_id`" => "howrs_id",
		"`howrs`.`howrs_howr1`" => "howrs_howr1",
		"`howrs`.`howrs_howr2`" => "howrs_howr2",
		"`howrs`.`howrs_howr3`" => "howrs_howr3",
		"`howrs`.`howrs_description`" => "howrs_description",
		"`howrs`.`howrs_created`" => "howrs_created",
		"`howrs`.`howrs_updated`" => "howrs_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`howrs`.`howrs_id`" => "Id",
		"`howrs`.`howrs_howr1`" => "Howr1 (Method)",
		"`howrs`.`howrs_howr2`" => "Howr2 (Type)",
		"`howrs`.`howrs_howr3`" => "Howr3 (Url If Any)",
		"`howrs`.`howrs_description`" => "Description",
		"`howrs`.`howrs_created`" => "Created AT",
		"`howrs`.`howrs_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`howrs`.`howrs_id`" => "howrs_id",
		"`howrs`.`howrs_howr1`" => "howrs_howr1",
		"`howrs`.`howrs_howr2`" => "howrs_howr2",
		"`howrs`.`howrs_howr3`" => "howrs_howr3",
		"`howrs`.`howrs_description`" => "howrs_description",
		"`howrs`.`howrs_created`" => "howrs_created",
		"`howrs`.`howrs_updated`" => "howrs_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`howrs` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'howrs_view.php';
	$x->TableTitle = 'Howrs (Method)';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`howrs`.`howrs_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Howr1 (Method)', 'Howr2 (Type)', 'Howr3 (Url If Any)', 'Description', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['howrs_id', 'howrs_howr1', 'howrs_howr2', 'howrs_howr3', 'howrs_description', 'howrs_created', 'howrs_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/howrs_templateTV.html';
	$x->SelectedTemplate = 'templates/howrs_templateTVS.html';
	$x->TemplateDV = 'templates/howrs_templateDV.html';
	$x->TemplateDVP = 'templates/howrs_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: howrs_init
	$render = true;
	if(function_exists('howrs_init')) {
		$args = [];
		$render = howrs_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: howrs_header
	$headerCode = '';
	if(function_exists('howrs_header')) {
		$args = [];
		$headerCode = howrs_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: howrs_footer
	$footerCode = '';
	if(function_exists('howrs_footer')) {
		$args = [];
		$footerCode = howrs_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
