<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/howss.php');
	include_once(__DIR__ . '/howss_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('howss');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'howss';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`howss`.`howss_id`" => "howss_id",
		"`howss`.`howss_hows1`" => "howss_hows1",
		"`howss`.`howss_hows2`" => "howss_hows2",
		"`howss`.`howss_hows3`" => "howss_hows3",
		"`howss`.`howss_description`" => "howss_description",
		"`howss`.`howss_created`" => "howss_created",
		"`howss`.`howss_updated`" => "howss_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`howss`.`howss_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`howss`.`howss_created`',
		7 => '`howss`.`howss_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`howss`.`howss_id`" => "howss_id",
		"`howss`.`howss_hows1`" => "howss_hows1",
		"`howss`.`howss_hows2`" => "howss_hows2",
		"`howss`.`howss_hows3`" => "howss_hows3",
		"`howss`.`howss_description`" => "howss_description",
		"`howss`.`howss_created`" => "howss_created",
		"`howss`.`howss_updated`" => "howss_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`howss`.`howss_id`" => "Id",
		"`howss`.`howss_hows1`" => "Hows1 (Medium)",
		"`howss`.`howss_hows2`" => "Hows2 (Format)",
		"`howss`.`howss_hows3`" => "Hows3 (Url If Any)",
		"`howss`.`howss_description`" => "Description",
		"`howss`.`howss_created`" => "Created AT",
		"`howss`.`howss_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`howss`.`howss_id`" => "howss_id",
		"`howss`.`howss_hows1`" => "howss_hows1",
		"`howss`.`howss_hows2`" => "howss_hows2",
		"`howss`.`howss_hows3`" => "howss_hows3",
		"`howss`.`howss_description`" => "howss_description",
		"`howss`.`howss_created`" => "howss_created",
		"`howss`.`howss_updated`" => "howss_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`howss` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'howss_view.php';
	$x->TableTitle = 'Howss (Steps)';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`howss`.`howss_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Hows1 (Medium)', 'Hows2 (Format)', 'Hows3 (Url If Any)', 'Description', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['howss_id', 'howss_hows1', 'howss_hows2', 'howss_hows3', 'howss_description', 'howss_created', 'howss_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/howss_templateTV.html';
	$x->SelectedTemplate = 'templates/howss_templateTVS.html';
	$x->TemplateDV = 'templates/howss_templateDV.html';
	$x->TemplateDVP = 'templates/howss_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: howss_init
	$render = true;
	if(function_exists('howss_init')) {
		$args = [];
		$render = howss_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: howss_header
	$headerCode = '';
	if(function_exists('howss_header')) {
		$args = [];
		$headerCode = howss_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: howss_footer
	$footerCode = '';
	if(function_exists('howss_footer')) {
		$args = [];
		$footerCode = howss_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
