<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/howts.php');
	include_once(__DIR__ . '/howts_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('howts');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'howts';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`howts`.`howts_id`" => "howts_id",
		"`howts`.`howts_howt1`" => "howts_howt1",
		"`howts`.`howts_howt2`" => "howts_howt2",
		"`howts`.`howts_howt3`" => "howts_howt3",
		"`howts`.`howrs_description`" => "howrs_description",
		"`howts`.`howrs_created`" => "howrs_created",
		"`howts`.`howrs_updated`" => "howrs_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`howts`.`howts_id`',
		2 => 2,
		3 => '`howts`.`howts_howt2`',
		4 => '`howts`.`howts_howt3`',
		5 => 5,
		6 => '`howts`.`howrs_created`',
		7 => '`howts`.`howrs_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`howts`.`howts_id`" => "howts_id",
		"`howts`.`howts_howt1`" => "howts_howt1",
		"`howts`.`howts_howt2`" => "howts_howt2",
		"`howts`.`howts_howt3`" => "howts_howt3",
		"`howts`.`howrs_description`" => "howrs_description",
		"`howts`.`howrs_created`" => "howrs_created",
		"`howts`.`howrs_updated`" => "howrs_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`howts`.`howts_id`" => "Id",
		"`howts`.`howts_howt1`" => "How (T) 1 (Type)",
		"`howts`.`howts_howt2`" => "How (T) 2 (Span)",
		"`howts`.`howts_howt3`" => "How (T) 3 (Target - if any)",
		"`howts`.`howrs_description`" => "Description",
		"`howts`.`howrs_created`" => "Created AT",
		"`howts`.`howrs_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`howts`.`howts_id`" => "howts_id",
		"`howts`.`howts_howt1`" => "howts_howt1",
		"`howts`.`howts_howt2`" => "howts_howt2",
		"`howts`.`howts_howt3`" => "howts_howt3",
		"`howts`.`howrs_description`" => "howrs_description",
		"`howts`.`howrs_created`" => "howrs_created",
		"`howts`.`howrs_updated`" => "howrs_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`howts` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'howts_view.php';
	$x->TableTitle = 'How (T) (Timespan)';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`howts`.`howts_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 100, ];
	$x->ColCaption = ['Id', 'How (T) 1 (Type)', 'How (T) 2 (Span)', 'How (T) 3 (Target - if any)', 'Description', 'Created AT', 'Updated AT', 'Madb', ];
	$x->ColFieldName = ['howts_id', 'howts_howt1', 'howts_howt2', 'howts_howt3', 'howrs_description', 'howrs_created', 'howrs_updated', '%madb.madb_howt1%', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, -1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/howts_templateTV.html';
	$x->SelectedTemplate = 'templates/howts_templateTVS.html';
	$x->TemplateDV = 'templates/howts_templateDV.html';
	$x->TemplateDVP = 'templates/howts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: howts_init
	$render = true;
	if(function_exists('howts_init')) {
		$args = [];
		$render = howts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: howts_header
	$headerCode = '';
	if(function_exists('howts_header')) {
		$args = [];
		$headerCode = howts_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: howts_footer
	$footerCode = '';
	if(function_exists('howts_footer')) {
		$args = [];
		$footerCode = howts_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
