<?php

// Data functions (insert, update, delete, form) for table ilct_info

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function ilct_info_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('ilct_info');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'ilct_info_title' => br2nl(Request::val('ilct_info_title', '')),
		'ilct_info_description' => br2nl(Request::val('ilct_info_description', '')),
		'ilct_info_link' => br2nl(Request::val('ilct_info_link', '')),
		'ilct_info_user' => br2nl(Request::val('ilct_info_user', '')),
		'ilct_info_pass' => br2nl(Request::val('ilct_info_pass', '')),
		'ilct_info_token' => br2nl(Request::val('ilct_info_token', '')),
		'ilct_info_pass_code' => br2nl(Request::val('ilct_info_pass_code', '')),
		'ilct_info_related_table' => Request::val('ilct_info_related_table', ''),
		'ilct_info_created' => parseCode('<%%creationTimestamp%%>', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('ilct_info', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		ilct_info_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function ilct_info_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function ilct_info_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('ilct_info', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: ilct_info_before_delete
	if(function_exists('ilct_info_before_delete')) {
		$args = [];
		if(!ilct_info_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `ilct_info` WHERE `ilct_info_id`='{$selected_id}'", $eo);

	// hook: ilct_info_after_delete
	if(function_exists('ilct_info_after_delete')) {
		$args = [];
		ilct_info_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='ilct_info' AND `pkValue`='{$selected_id}'", $eo);
}

function ilct_info_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('ilct_info', $selected_id, 'edit')) return false;

	$data = [
		'ilct_info_title' => br2nl(Request::val('ilct_info_title', '')),
		'ilct_info_description' => br2nl(Request::val('ilct_info_description', '')),
		'ilct_info_link' => br2nl(Request::val('ilct_info_link', '')),
		'ilct_info_user' => br2nl(Request::val('ilct_info_user', '')),
		'ilct_info_pass' => br2nl(Request::val('ilct_info_pass', '')),
		'ilct_info_token' => br2nl(Request::val('ilct_info_token', '')),
		'ilct_info_pass_code' => br2nl(Request::val('ilct_info_pass_code', '')),
		'ilct_info_related_table' => Request::val('ilct_info_related_table', ''),
		'ilct_info_updated' => parseCode('<%%editingTimestamp%%>', false, true),
	];

	if($data['ilct_info_title'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'ILCT INFO Title': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('ilct_info', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: ilct_info_before_update
	if(function_exists('ilct_info_before_update')) {
		$args = ['old_data' => $old_data];
		if(!ilct_info_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'ilct_info',
		backtick_keys_once($set),
		['`ilct_info_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="ilct_info_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('ilct_info', $data['selectedID'], calculated_fields()['ilct_info']);

	// hook: ilct_info_after_update
	if(function_exists('ilct_info_after_update')) {
		if($row = getRecord('ilct_info', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ilct_info_id'];
		$args = ['old_data' => $old_data];
		if(!ilct_info_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('ilct_info', $selected_id);
}

function ilct_info_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('ilct_info');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('ilct_info', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('ilct_info', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('ilct_info', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: ilct_info_related_table
	$combo_ilct_info_related_table = new Combo;
	$combo_ilct_info_related_table->ListType = 0;
	$combo_ilct_info_related_table->MultipleSeparator = ', ';
	$combo_ilct_info_related_table->ListBoxHeight = 10;
	$combo_ilct_info_related_table->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/ilct_info.ilct_info_related_table.csv')) {
		$ilct_info_related_table_data = addslashes(implode('', @file(__DIR__ . '/hooks/ilct_info.ilct_info_related_table.csv')));
		$combo_ilct_info_related_table->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($ilct_info_related_table_data))));
		$combo_ilct_info_related_table->ListData = $combo_ilct_info_related_table->ListItem;
	} else {
		$combo_ilct_info_related_table->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("MADB;;WHATS;;WHOS;;WHENS;;WHICHS;;WHERES;;WHYS;;HOWRS;;HOWSS;;HOWQS;;HOWTS;;UTEDB;;PREMISES;;PNB;;ILCT_INFO"))));
		$combo_ilct_info_related_table->ListData = $combo_ilct_info_related_table->ListItem;
	}
	$combo_ilct_info_related_table->SelectName = 'ilct_info_related_table';

	if($hasSelectedId) {
		if(!($row = getRecord('ilct_info', $selectedId))) {
			return error_message($Translation['No records found'], 'ilct_info_view.php', false);
		}
		$combo_ilct_info_related_table->SelectedData = $row['ilct_info_related_table'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_ilct_info_related_table->SelectedText = (isset($filterField[1]) && $filterField[1] == '9' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_ilct_info_related_table->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		$j(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/ilct_info_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/ilct_info_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'IMPORTANT LCT INFO Details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#ilct_info_title').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_title\">' + (\$j('#ilct_info_title').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ilct_info_description').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_description\">' + (\$j('#ilct_info_description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ilct_info_link').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_link\">' + (\$j('#ilct_info_link').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ilct_info_user').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_user\">' + (\$j('#ilct_info_user').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ilct_info_pass').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_pass\">' + (\$j('#ilct_info_pass').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ilct_info_token').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_token\">' + (\$j('#ilct_info_token').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ilct_info_pass_code').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_pass_code\">' + (\$j('#ilct_info_pass_code').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ilct_info_related_table').replaceWith('<div class=\"form-control-static\" id=\"ilct_info_related_table\">' + (\$j('#ilct_info_related_table').val() || '') + '</div>'); \$j('#ilct_info_related_table-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(ilct_info_related_table)%%>', $combo_ilct_info_related_table->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ilct_info_related_table)%%>', $combo_ilct_info_related_table->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_title)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_link)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_user)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_pass)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_token)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_pass_code)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_related_table)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_created)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ilct_info_updated)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ilct_info_id)%%>', safe_html($urow['ilct_info_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ilct_info_id)%%>', html_attr($row['ilct_info_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_id)%%>', urlencode($urow['ilct_info_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_title)%%>', safe_html($urow['ilct_info_title'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_title)%%>', urlencode($urow['ilct_info_title']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_description)%%>', safe_html($urow['ilct_info_description'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_description)%%>', urlencode($urow['ilct_info_description']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_link)%%>', safe_html($urow['ilct_info_link'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_link)%%>', urlencode($urow['ilct_info_link']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_user)%%>', safe_html($urow['ilct_info_user'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_user)%%>', urlencode($urow['ilct_info_user']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_pass)%%>', safe_html($urow['ilct_info_pass'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_pass)%%>', urlencode($urow['ilct_info_pass']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_token)%%>', safe_html($urow['ilct_info_token'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_token)%%>', urlencode($urow['ilct_info_token']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_pass_code)%%>', safe_html($urow['ilct_info_pass_code'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_pass_code)%%>', urlencode($urow['ilct_info_pass_code']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ilct_info_related_table)%%>', safe_html($urow['ilct_info_related_table']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ilct_info_related_table)%%>', html_attr($row['ilct_info_related_table']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_related_table)%%>', urlencode($urow['ilct_info_related_table']), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_created)%%>', time12(html_attr($row['ilct_info_created'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_created)%%>', urlencode(time12($urow['ilct_info_created'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_updated)%%>', safe_html($urow['ilct_info_updated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_updated)%%>', urlencode($urow['ilct_info_updated']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ilct_info_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_title)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_title)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_link)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_link)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_user)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_user)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_pass)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_pass)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_token)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_token)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_pass_code)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_pass_code)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_related_table)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_related_table)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_created)%%>', '<%%creationTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_created)%%>', urlencode('<%%creationTimestamp%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(ilct_info_updated)%%>', '<%%editingTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ilct_info_updated)%%>', urlencode('<%%editingTimestamp%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('ilct_info');
	if($hasSelectedId) {
		$jdata = get_joined_record('ilct_info', $selectedId);
		if($jdata === false) $jdata = get_defaults('ilct_info');
		$rdata = $row;
	}
	$templateCode .= loadView('ilct_info-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: ilct_info_dv
	if(function_exists('ilct_info_dv')) {
		$args = [];
		ilct_info_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}