<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/madb.php');
	include_once(__DIR__ . '/madb_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('madb');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'madb';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`madb`.`madb_id`" => "madb_id",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `whats1`.`whats_what1`), '') /* What1 */" => "madb_what1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who1 */" => "madb_who1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when1`) || CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when1`, '-', `whens1`.`whens_when2`), '') /* When1 */" => "madb_when1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which1 */" => "madb_which1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where1 */" => "madb_where1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why1 */" => "madb_why1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why2 */" => "madb_why2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why3 */" => "madb_why3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where2 */" => "madb_where2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where3 */" => "madb_where3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which2 */" => "madb_which2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which3 */" => "madb_which3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When2 */" => "madb_when2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When3 */" => "madb_when3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who2 */" => "madb_who2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who3 */" => "madb_who3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What2 */" => "madb_what2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What3 */" => "madb_what3",
		"`madb`.`madb_created`" => "madb_created",
		"`madb`.`madb_updated`" => "madb_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`madb`.`madb_id`',
		2 => '`whats1`.`whats_what1`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`whys1`.`whys_why2`',
		9 => '`whys1`.`whys_why3`',
		10 => '`wheres1`.`wheres_where2`',
		11 => '`wheres1`.`wheres_where3`',
		12 => '`whichs1`.`whichs_which2`',
		13 => '`whichs1`.`whichs_which3`',
		14 => '`whens1`.`whens_when2`',
		15 => 'time_format(`whens1`.`whens_when3`,\'%r\')',
		16 => '`whos1`.`whos_who2`',
		17 => '`whos1`.`whos_who3`',
		18 => '`whats1`.`whats_what2`',
		19 => '`whats1`.`whats_what3`',
		20 => '`madb`.`madb_created`',
		21 => '`madb`.`madb_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`madb`.`madb_id`" => "madb_id",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `whats1`.`whats_what1`), '') /* What1 */" => "madb_what1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who1 */" => "madb_who1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when1`) || CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when1`, '-', `whens1`.`whens_when2`), '') /* When1 */" => "madb_when1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which1 */" => "madb_which1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where1 */" => "madb_where1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why1 */" => "madb_why1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why2 */" => "madb_why2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why3 */" => "madb_why3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where2 */" => "madb_where2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where3 */" => "madb_where3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which2 */" => "madb_which2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which3 */" => "madb_which3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When2 */" => "madb_when2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When3 */" => "madb_when3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who2 */" => "madb_who2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who3 */" => "madb_who3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What2 */" => "madb_what2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What3 */" => "madb_what3",
		"`madb`.`madb_created`" => "madb_created",
		"`madb`.`madb_updated`" => "madb_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`madb`.`madb_id`" => "Id",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `whats1`.`whats_what1`), '') /* What1 */" => "What1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who1 */" => "Who1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when1`) || CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when1`, '-', `whens1`.`whens_when2`), '') /* When1 */" => "When1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which1 */" => "Which1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where1 */" => "Where1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why1 */" => "Why1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why2 */" => "Why2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why3 */" => "Why3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where2 */" => "Where2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where3 */" => "Where3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which2 */" => "Which2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which3 */" => "Which3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When2 */" => "When2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When3 */" => "When3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who2 */" => "Who2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who3 */" => "Who3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What2 */" => "What2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What3 */" => "What3",
		"`madb`.`madb_created`" => "Created AT",
		"`madb`.`madb_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`madb`.`madb_id`" => "madb_id",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `whats1`.`whats_what1`), '') /* What1 */" => "madb_what1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who1 */" => "madb_who1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when1`) || CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when1`, '-', `whens1`.`whens_when2`), '') /* When1 */" => "madb_when1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which1 */" => "madb_which1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where1 */" => "madb_where1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why1 */" => "madb_why1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why2 */" => "madb_why2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why3 */" => "madb_why3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where2 */" => "madb_where2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where3 */" => "madb_where3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which2 */" => "madb_which2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which3 */" => "madb_which3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When2 */" => "madb_when2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When3 */" => "madb_when3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who2 */" => "madb_who2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who3 */" => "madb_who3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What2 */" => "madb_what2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What3 */" => "madb_what3",
		"`madb`.`madb_created`" => "madb_created",
		"`madb`.`madb_updated`" => "madb_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['madb_what1' => 'What1', 'madb_who1' => 'Who1', 'madb_when1' => 'When1', 'madb_which1' => 'Which1', 'madb_where1' => 'Where1', 'madb_why1' => 'Why1', ];

	$x->QueryFrom = "`madb` LEFT JOIN `whats` as whats1 ON `whats1`.`whats_id`=`madb`.`madb_what1` LEFT JOIN `whos` as whos1 ON `whos1`.`whos_id`=`madb`.`madb_who1` LEFT JOIN `whens` as whens1 ON `whens1`.`whens_id`=`madb`.`madb_when1` LEFT JOIN `whichs` as whichs1 ON `whichs1`.`whichs_id`=`madb`.`madb_which1` LEFT JOIN `wheres` as wheres1 ON `wheres1`.`wheres_id`=`madb`.`madb_where1` LEFT JOIN `whys` as whys1 ON `whys1`.`whys_id`=`madb`.`madb_why1` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 500;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'madb_view.php';
	$x->TableTitle = 'Master Anatomy DB';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`madb`.`madb_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'What1', 'Who1', 'When1', 'Which1', 'Where1', 'Why1', 'Why2', 'Why3', 'Where2', 'Where3', 'Which2', 'Which3', 'When2', 'When3', 'Who2', 'Who3', 'What2', 'What3', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['madb_id', 'madb_what1', 'madb_who1', 'madb_when1', 'madb_which1', 'madb_where1', 'madb_why1', 'madb_why2', 'madb_why3', 'madb_where2', 'madb_where3', 'madb_which2', 'madb_which3', 'madb_when2', 'madb_when3', 'madb_who2', 'madb_who3', 'madb_what2', 'madb_what3', 'madb_created', 'madb_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/madb_templateTV.html';
	$x->SelectedTemplate = 'templates/madb_templateTVS.html';
	$x->TemplateDV = 'templates/madb_templateDV.html';
	$x->TemplateDVP = 'templates/madb_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: madb_init
	$render = true;
	if(function_exists('madb_init')) {
		$args = [];
		$render = madb_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: madb_header
	$headerCode = '';
	if(function_exists('madb_header')) {
		$args = [];
		$headerCode = madb_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: madb_footer
	$footerCode = '';
	if(function_exists('madb_footer')) {
		$args = [];
		$footerCode = madb_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
