<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('madb');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = Request::val('mfk');
	$id = makeSafe(Request::val('id'));
	$rnd1 = intval(Request::val('rnd1')); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'madb_what1':
			if(!$id) {
				?>
				$j('#madb_what2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_what3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `whats`.`whats_id` as 'whats_id', `whats`.`whats_what1` as 'whats_what1', `whats`.`whats_what2` as 'whats_what2', `whats`.`whats_what3` as 'whats_what3', `whats`.`whats_description` as 'whats_description', `whats`.`whats_created` as 'whats_created', `whats`.`whats_updated` as 'whats_updated' FROM `whats`  WHERE `whats`.`whats_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_what2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whats_what2']))); ?>&nbsp;');
			$j('#madb_what3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whats_what3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_who1':
			if(!$id) {
				?>
				$j('#madb_who2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_who3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `whos`.`whos_id` as 'whos_id', `whos`.`whos_who1` as 'whos_who1', `whos`.`whos_who2` as 'whos_who2', `whos`.`whos_who3` as 'whos_who3', `whos`.`whos_description` as 'whos_description', `whos`.`whos_swg_token` as 'whos_swg_token', `whos`.`whos_swg_email` as 'whos_swg_email', IF(    CHAR_LENGTH(`premises1`.`premises_name`) || CHAR_LENGTH(`premises1`.`premises_radius`), CONCAT_WS('',   `premises1`.`premises_name`, '-', `premises1`.`premises_radius`), '') as 'whos_premise', `whos`.`whos_created` as 'whos_created', `whos`.`whos_updated` as 'whos_updated' FROM `whos` LEFT JOIN `premises` as premises1 ON `premises1`.`premises_id`=`whos`.`whos_premise`  WHERE `whos`.`whos_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_who2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whos_who2']))); ?>&nbsp;');
			$j('#madb_who3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whos_who3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_when1':
			if(!$id) {
				?>
				$j('#madb_when2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_when3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `whens`.`whens_id` as 'whens_id', `whens`.`whens_when1` as 'whens_when1', `whens`.`whens_when2` as 'whens_when2', TIME_FORMAT(`whens`.`whens_when3`, '%r') as 'whens_when3', `whens`.`whens_description` as 'whens_description', `whens`.`whens_created` as 'whens_created', `whens`.`whens_updated` as 'whens_updated' FROM `whens`  WHERE `whens`.`whens_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_when2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whens_when2']))); ?>&nbsp;');
			$j('#madb_when3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whens_when3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_which1':
			if(!$id) {
				?>
				$j('#madb_which2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_which3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `whichs`.`whichs_id` as 'whichs_id', `whichs`.`whichs_which1` as 'whichs_which1', `whichs`.`whichs_which2` as 'whichs_which2', `whichs`.`whichs_which3` as 'whichs_which3', `whichs`.`whichs_description` as 'whichs_description', `whichs`.`whichs_created` as 'whichs_created', `whichs`.`whichs_updated` as 'whichs_updated' FROM `whichs`  WHERE `whichs`.`whichs_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_which2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whichs_which2']))); ?>&nbsp;');
			$j('#madb_which3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whichs_which3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_where1':
			if(!$id) {
				?>
				$j('#madb_where2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_where3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `wheres`.`wheres_id` as 'wheres_id', `wheres`.`wheres_where1` as 'wheres_where1', `wheres`.`wheres_where2` as 'wheres_where2', `wheres`.`wheres_where3` as 'wheres_where3', `wheres`.`wheres_description` as 'wheres_description', `wheres`.`wheres_created` as 'wheres_created', `wheres`.`wheres_updated` as 'wheres_updated' FROM `wheres`  WHERE `wheres`.`wheres_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_where2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['wheres_where2']))); ?>&nbsp;');
			$j('#madb_where3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['wheres_where3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_why1':
			if(!$id) {
				?>
				$j('#madb_why2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_why3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `whys`.`whys_id` as 'whys_id', `whys`.`whys_why1` as 'whys_why1', `whys`.`whys_why2` as 'whys_why2', `whys`.`whys_why3` as 'whys_why3', `whys`.`whys_description` as 'whys_description', `whys`.`whys_created` as 'whys_created', `whys`.`whys_updated` as 'whys_updated' FROM `whys`  WHERE `whys`.`whys_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_why2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whys_why2']))); ?>&nbsp;');
			$j('#madb_why3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['whys_why3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_howr1':
			if(!$id) {
				?>
				$j('#madb_howr2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_howr3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `howrs`.`howrs_id` as 'howrs_id', `howrs`.`howrs_howr1` as 'howrs_howr1', `howrs`.`howrs_howr2` as 'howrs_howr2', `howrs`.`howrs_howr3` as 'howrs_howr3', `howrs`.`howrs_description` as 'howrs_description', `howrs`.`howrs_created` as 'howrs_created', `howrs`.`howrs_updated` as 'howrs_updated' FROM `howrs`  WHERE `howrs`.`howrs_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_howr2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howrs_howr2']))); ?>&nbsp;');
			$j('#madb_howr3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howrs_howr3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_hows1':
			if(!$id) {
				?>
				$j('#madb_hows2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_hows3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `howss`.`howss_id` as 'howss_id', `howss`.`howss_hows1` as 'howss_hows1', `howss`.`howss_hows2` as 'howss_hows2', `howss`.`howss_hows3` as 'howss_hows3', `howss`.`howss_hows4` as 'howss_hows4', `howss`.`howss_description` as 'howss_description', `howss`.`howss_created` as 'howss_created', `howss`.`howss_updated` as 'howss_updated' FROM `howss`  WHERE `howss`.`howss_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_hows2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howss_hows2']))); ?>&nbsp;');
			$j('#madb_hows3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howss_hows3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_howq1':
			if(!$id) {
				?>
				$j('#madb_howq2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_howq3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `howqs`.`howqs_id` as 'howqs_id', `howqs`.`howqs_howq1` as 'howqs_howq1', `howqs`.`howqs_howq2` as 'howqs_howq2', `howqs`.`howqs_howq3` as 'howqs_howq3', `howqs`.`howqs_description` as 'howqs_description', `howqs`.`howqs_created` as 'howqs_created', `howqs`.`howqs_updated` as 'howqs_updated' FROM `howqs`  WHERE `howqs`.`howqs_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_howq2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howqs_howq3']))); ?>&nbsp;');
			$j('#madb_howq3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howqs_howq3']))); ?>&nbsp;');
			<?php
			break;

		case 'madb_howt1':
			if(!$id) {
				?>
				$j('#madb_howt2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#madb_howt3<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `howts`.`howts_id` as 'howts_id', `howts`.`howts_howt1` as 'howts_howt1', `howts`.`howts_howt2` as 'howts_howt2', `howts`.`howts_howt3` as 'howts_howt3', `howts`.`howrs_description` as 'howrs_description', `howts`.`howrs_created` as 'howrs_created', `howts`.`howrs_updated` as 'howrs_updated' FROM `howts`  WHERE `howts`.`howts_id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#madb_howt2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howts_howt2']))); ?>&nbsp;');
			$j('#madb_howt3<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['howts_howt3']))); ?>&nbsp;');
			<?php
			break;


	}

?>