<?php

// Data functions (insert, update, delete, form) for table pnb

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function pnb_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('pnb');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'pnb_type' => Request::val('pnb_type', ''),
		'pnb_premises_id' => Request::lookup('pnb_premises_id', ''),
		'pnb_whos_id' => Request::lookup('pnb_whos_id', ''),
		'pnb_created' => parseCode('<%%creationTimestamp%%>', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('pnb', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		pnb_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function pnb_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function pnb_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('pnb', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: pnb_before_delete
	if(function_exists('pnb_before_delete')) {
		$args = [];
		if(!pnb_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `pnb` WHERE `pnb_id`='{$selected_id}'", $eo);

	// hook: pnb_after_delete
	if(function_exists('pnb_after_delete')) {
		$args = [];
		pnb_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='pnb' AND `pkValue`='{$selected_id}'", $eo);
}

function pnb_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('pnb', $selected_id, 'edit')) return false;

	$data = [
		'pnb_type' => Request::val('pnb_type', ''),
		'pnb_premises_id' => Request::lookup('pnb_premises_id', ''),
		'pnb_whos_id' => Request::lookup('pnb_whos_id', ''),
		'pnb_updated' => parseCode('<%%editingTimestamp%%>', false, true),
	];

	// get existing values
	$old_data = getRecord('pnb', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: pnb_before_update
	if(function_exists('pnb_before_update')) {
		$args = ['old_data' => $old_data];
		if(!pnb_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'pnb',
		backtick_keys_once($set),
		['`pnb_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="pnb_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('pnb', $data['selectedID'], calculated_fields()['pnb']);

	// hook: pnb_after_update
	if(function_exists('pnb_after_update')) {
		if($row = getRecord('pnb', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['pnb_id'];
		$args = ['old_data' => $old_data];
		if(!pnb_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('pnb', $selected_id);
}

function pnb_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('pnb');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('pnb', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('pnb', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('pnb', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_pnb_premises_id = Request::val('filterer_pnb_premises_id');
	$filterer_pnb_whos_id = Request::val('filterer_pnb_whos_id');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: pnb_type
	$combo_pnb_type = new Combo;
	$combo_pnb_type->ListType = 0;
	$combo_pnb_type->MultipleSeparator = ', ';
	$combo_pnb_type->ListBoxHeight = 10;
	$combo_pnb_type->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/pnb.pnb_type.csv')) {
		$pnb_type_data = addslashes(implode('', @file(__DIR__ . '/hooks/pnb.pnb_type.csv')));
		$combo_pnb_type->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($pnb_type_data))));
		$combo_pnb_type->ListData = $combo_pnb_type->ListItem;
	} else {
		$combo_pnb_type->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("In;;Out;;Absent;;Leave"))));
		$combo_pnb_type->ListData = $combo_pnb_type->ListItem;
	}
	$combo_pnb_type->SelectName = 'pnb_type';
	// combobox: pnb_premises_id
	$combo_pnb_premises_id = new DataCombo;
	// combobox: pnb_whos_id
	$combo_pnb_whos_id = new DataCombo;

	if($hasSelectedId) {
		if(!($row = getRecord('pnb', $selectedId))) {
			return error_message($Translation['No records found'], 'pnb_view.php', false);
		}
		$combo_pnb_type->SelectedData = $row['pnb_type'];
		$combo_pnb_premises_id->SelectedData = $row['pnb_premises_id'];
		$combo_pnb_whos_id->SelectedData = $row['pnb_whos_id'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_pnb_type->SelectedText = (isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_pnb_premises_id->SelectedData = $filterer_pnb_premises_id;
		$combo_pnb_whos_id->SelectedData = $filterer_pnb_whos_id;
	}
	$combo_pnb_type->Render();
	$combo_pnb_premises_id->HTML = '<span id="pnb_premises_id-container' . $rnd1 . '"></span><input type="hidden" name="pnb_premises_id" id="pnb_premises_id' . $rnd1 . '" value="' . html_attr($combo_pnb_premises_id->SelectedData) . '">';
	$combo_pnb_premises_id->MatchText = '<span id="pnb_premises_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="pnb_premises_id" id="pnb_premises_id' . $rnd1 . '" value="' . html_attr($combo_pnb_premises_id->SelectedData) . '">';
	$combo_pnb_whos_id->HTML = '<span id="pnb_whos_id-container' . $rnd1 . '"></span><input type="hidden" name="pnb_whos_id" id="pnb_whos_id' . $rnd1 . '" value="' . html_attr($combo_pnb_whos_id->SelectedData) . '">';
	$combo_pnb_whos_id->MatchText = '<span id="pnb_whos_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="pnb_whos_id" id="pnb_whos_id' . $rnd1 . '" value="' . html_attr($combo_pnb_whos_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_pnb_premises_id__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['pnb_premises_id'] : htmlspecialchars($filterer_pnb_premises_id, ENT_QUOTES)); ?>"};
		AppGini.current_pnb_whos_id__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['pnb_whos_id'] : htmlspecialchars($filterer_pnb_whos_id, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(pnb_premises_id_reload__RAND__) == 'function') pnb_premises_id_reload__RAND__();
				if(typeof(pnb_whos_id_reload__RAND__) == 'function') pnb_whos_id_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function pnb_premises_id_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#pnb_premises_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_pnb_premises_id__RAND__.value, t: 'pnb', f: 'pnb_premises_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="pnb_premises_id"]').val(resp.results[0].id);
							$j('[id=pnb_premises_id-container-readonly__RAND__]').html('<span class="match-text" id="pnb_premises_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=premises_view_parent]').hide(); } else { $j('.btn[id=premises_view_parent]').show(); }


							if(typeof(pnb_premises_id_update_autofills__RAND__) == 'function') pnb_premises_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'pnb', f: 'pnb_premises_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_pnb_premises_id__RAND__.value = e.added.id;
				AppGini.current_pnb_premises_id__RAND__.text = e.added.text;
				$j('[name="pnb_premises_id"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=premises_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(pnb_premises_id_update_autofills__RAND__) == 'function') pnb_premises_id_update_autofills__RAND__();
			});

			if(!$j("#pnb_premises_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_pnb_premises_id__RAND__.value, t: 'pnb', f: 'pnb_premises_id' },
					success: function(resp) {
						$j('[name="pnb_premises_id"]').val(resp.results[0].id);
						$j('[id=pnb_premises_id-container-readonly__RAND__]').html('<span class="match-text" id="pnb_premises_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=premises_view_parent]').hide(); } else { $j('.btn[id=premises_view_parent]').show(); }

						if(typeof(pnb_premises_id_update_autofills__RAND__) == 'function') pnb_premises_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_pnb_premises_id__RAND__.value, t: 'pnb', f: 'pnb_premises_id' },
				success: function(resp) {
					$j('[id=pnb_premises_id-container__RAND__], [id=pnb_premises_id-container-readonly__RAND__]').html('<span class="match-text" id="pnb_premises_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=premises_view_parent]').hide(); } else { $j('.btn[id=premises_view_parent]').show(); }

					if(typeof(pnb_premises_id_update_autofills__RAND__) == 'function') pnb_premises_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function pnb_whos_id_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#pnb_whos_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_pnb_whos_id__RAND__.value, t: 'pnb', f: 'pnb_whos_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="pnb_whos_id"]').val(resp.results[0].id);
							$j('[id=pnb_whos_id-container-readonly__RAND__]').html('<span class="match-text" id="pnb_whos_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whos_view_parent]').hide(); } else { $j('.btn[id=whos_view_parent]').show(); }


							if(typeof(pnb_whos_id_update_autofills__RAND__) == 'function') pnb_whos_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'pnb', f: 'pnb_whos_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_pnb_whos_id__RAND__.value = e.added.id;
				AppGini.current_pnb_whos_id__RAND__.text = e.added.text;
				$j('[name="pnb_whos_id"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=whos_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(pnb_whos_id_update_autofills__RAND__) == 'function') pnb_whos_id_update_autofills__RAND__();
			});

			if(!$j("#pnb_whos_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_pnb_whos_id__RAND__.value, t: 'pnb', f: 'pnb_whos_id' },
					success: function(resp) {
						$j('[name="pnb_whos_id"]').val(resp.results[0].id);
						$j('[id=pnb_whos_id-container-readonly__RAND__]').html('<span class="match-text" id="pnb_whos_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whos_view_parent]').hide(); } else { $j('.btn[id=whos_view_parent]').show(); }

						if(typeof(pnb_whos_id_update_autofills__RAND__) == 'function') pnb_whos_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_pnb_whos_id__RAND__.value, t: 'pnb', f: 'pnb_whos_id' },
				success: function(resp) {
					$j('[id=pnb_whos_id-container__RAND__], [id=pnb_whos_id-container-readonly__RAND__]').html('<span class="match-text" id="pnb_whos_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whos_view_parent]').hide(); } else { $j('.btn[id=whos_view_parent]').show(); }

					if(typeof(pnb_whos_id_update_autofills__RAND__) == 'function') pnb_whos_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/pnb_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/pnb_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Pnb details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#pnb_type').replaceWith('<div class=\"form-control-static\" id=\"pnb_type\">' + (\$j('#pnb_type').val() || '') + '</div>'); \$j('#pnb_type-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#pnb_premises_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#pnb_premises_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#pnb_whos_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#pnb_whos_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(pnb_type)%%>', $combo_pnb_type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(pnb_type)%%>', $combo_pnb_type->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(pnb_premises_id)%%>', $combo_pnb_premises_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(pnb_premises_id)%%>', $combo_pnb_premises_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(pnb_premises_id)%%>', urlencode($combo_pnb_premises_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(pnb_whos_id)%%>', $combo_pnb_whos_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(pnb_whos_id)%%>', $combo_pnb_whos_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(pnb_whos_id)%%>', urlencode($combo_pnb_whos_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['pnb_premises_id' => ['premises', 'Premises Id'], 'pnb_whos_id' => ['whos', 'Whos Id'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(pnb_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pnb_type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pnb_premises_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pnb_whos_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pnb_created)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pnb_updated)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pnb_id)%%>', safe_html($urow['pnb_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pnb_id)%%>', html_attr($row['pnb_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_id)%%>', urlencode($urow['pnb_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pnb_type)%%>', safe_html($urow['pnb_type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pnb_type)%%>', html_attr($row['pnb_type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_type)%%>', urlencode($urow['pnb_type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pnb_premises_id)%%>', safe_html($urow['pnb_premises_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pnb_premises_id)%%>', html_attr($row['pnb_premises_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_premises_id)%%>', urlencode($urow['pnb_premises_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pnb_whos_id)%%>', safe_html($urow['pnb_whos_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pnb_whos_id)%%>', html_attr($row['pnb_whos_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_whos_id)%%>', urlencode($urow['pnb_whos_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(pnb_created)%%>', safe_html($urow['pnb_created']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_created)%%>', urlencode($urow['pnb_created']), $templateCode);
		$templateCode = str_replace('<%%VALUE(pnb_updated)%%>', safe_html($urow['pnb_updated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_updated)%%>', urlencode($urow['pnb_updated']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(pnb_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pnb_type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pnb_premises_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_premises_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pnb_whos_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_whos_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pnb_created)%%>', '<%%creationTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_created)%%>', urlencode('<%%creationTimestamp%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(pnb_updated)%%>', '<%%editingTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pnb_updated)%%>', urlencode('<%%editingTimestamp%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('pnb');
	if($hasSelectedId) {
		$jdata = get_joined_record('pnb', $selectedId);
		if($jdata === false) $jdata = get_defaults('pnb');
		$rdata = $row;
	}
	$templateCode .= loadView('pnb-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: pnb_dv
	if(function_exists('pnb_dv')) {
		$args = [];
		pnb_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}