<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/pnb.php');
	include_once(__DIR__ . '/pnb_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('pnb');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'pnb';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`pnb`.`pnb_id`" => "pnb_id",
		"`pnb`.`pnb_type`" => "pnb_type",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "pnb_premises_id",
		"IF(    CHAR_LENGTH(`whos1`.`whos_id`) || CHAR_LENGTH(`whos1`.`whos_who1`), CONCAT_WS('',   `whos1`.`whos_id`, '-', `whos1`.`whos_who1`), '') /* Whos Id */" => "pnb_whos_id",
		"`pnb`.`pnb_created`" => "pnb_created",
		"`pnb`.`pnb_updated`" => "pnb_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`pnb`.`pnb_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`pnb`.`pnb_created`',
		6 => '`pnb`.`pnb_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`pnb`.`pnb_id`" => "pnb_id",
		"`pnb`.`pnb_type`" => "pnb_type",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "pnb_premises_id",
		"IF(    CHAR_LENGTH(`whos1`.`whos_id`) || CHAR_LENGTH(`whos1`.`whos_who1`), CONCAT_WS('',   `whos1`.`whos_id`, '-', `whos1`.`whos_who1`), '') /* Whos Id */" => "pnb_whos_id",
		"`pnb`.`pnb_created`" => "pnb_created",
		"`pnb`.`pnb_updated`" => "pnb_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`pnb`.`pnb_id`" => "Pnb id",
		"`pnb`.`pnb_type`" => "Pnb type",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "Premises Id",
		"IF(    CHAR_LENGTH(`whos1`.`whos_id`) || CHAR_LENGTH(`whos1`.`whos_who1`), CONCAT_WS('',   `whos1`.`whos_id`, '-', `whos1`.`whos_who1`), '') /* Whos Id */" => "Whos Id",
		"`pnb`.`pnb_created`" => "Pnb created",
		"`pnb`.`pnb_updated`" => "Pnb updated",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`pnb`.`pnb_id`" => "pnb_id",
		"`pnb`.`pnb_type`" => "pnb_type",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "pnb_premises_id",
		"IF(    CHAR_LENGTH(`whos1`.`whos_id`) || CHAR_LENGTH(`whos1`.`whos_who1`), CONCAT_WS('',   `whos1`.`whos_id`, '-', `whos1`.`whos_who1`), '') /* Whos Id */" => "pnb_whos_id",
		"`pnb`.`pnb_created`" => "pnb_created",
		"`pnb`.`pnb_updated`" => "pnb_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['pnb_premises_id' => 'Premises Id', 'pnb_whos_id' => 'Whos Id', ];

	$x->QueryFrom = "`pnb` LEFT JOIN `premises` as premises1 ON `premises1`.`premises_id`=`pnb`.`pnb_premises_id` LEFT JOIN `whos` as whos1 ON `whos1`.`whos_id`=`pnb`.`pnb_whos_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'pnb_view.php';
	$x->TableTitle = 'Presence & Being';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`pnb`.`pnb_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Pnb id', 'Pnb type', 'Premises Id', 'Whos Id', 'Pnb created', 'Pnb updated', ];
	$x->ColFieldName = ['pnb_id', 'pnb_type', 'pnb_premises_id', 'pnb_whos_id', 'pnb_created', 'pnb_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/pnb_templateTV.html';
	$x->SelectedTemplate = 'templates/pnb_templateTVS.html';
	$x->TemplateDV = 'templates/pnb_templateDV.html';
	$x->TemplateDVP = 'templates/pnb_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: pnb_init
	$render = true;
	if(function_exists('pnb_init')) {
		$args = [];
		$render = pnb_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: pnb_header
	$headerCode = '';
	if(function_exists('pnb_header')) {
		$args = [];
		$headerCode = pnb_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: pnb_footer
	$footerCode = '';
	if(function_exists('pnb_footer')) {
		$args = [];
		$footerCode = pnb_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
