<?php

// Data functions (insert, update, delete, form) for table premises

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function premises_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('premises');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'premises_name' => Request::val('premises_name', ''),
		'premises_latitude' => Request::val('premises_latitude', ''),
		'premises_longitude' => Request::val('premises_longitude', ''),
		'premises_radius' => Request::val('premises_radius', ''),
		'premises_opening' => Request::lookup('premises_opening', ''),
		'premises_closing' => Request::lookup('premises_closing', ''),
		'premises_created' => parseCode('<%%creationTimestamp%%>', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('premises', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		premises_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function premises_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function premises_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('premises', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: premises_before_delete
	if(function_exists('premises_before_delete')) {
		$args = [];
		if(!premises_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	// child table: madb
	$res = sql("SELECT `premises_id` FROM `premises` WHERE `premises_id`='{$selected_id}'", $eo);
	$premises_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `madb` WHERE `madb_premises_id`='" . makeSafe($premises_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="madb_view.php?filterer_madb_premises_id=' . urlencode($premises_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'madb'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'madb'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: whos
	$res = sql("SELECT `premises_id` FROM `premises` WHERE `premises_id`='{$selected_id}'", $eo);
	$premises_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `whos` WHERE `whos_premise`='" . makeSafe($premises_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="whos_view.php?filterer_whos_premise=' . urlencode($premises_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'whos'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'whos'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: utedb
	$res = sql("SELECT `premises_id` FROM `premises` WHERE `premises_id`='{$selected_id}'", $eo);
	$premises_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `utedb` WHERE `utedb_premises_id`='" . makeSafe($premises_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="utedb_view.php?filterer_utedb_premises_id=' . urlencode($premises_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'utedb'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'utedb'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: pnb
	$res = sql("SELECT `premises_id` FROM `premises` WHERE `premises_id`='{$selected_id}'", $eo);
	$premises_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `pnb` WHERE `pnb_premises_id`='" . makeSafe($premises_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="pnb_view.php?filterer_pnb_premises_id=' . urlencode($premises_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'pnb'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'pnb'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `premises_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `premises` WHERE `premises_id`='{$selected_id}'", $eo);

	// hook: premises_after_delete
	if(function_exists('premises_after_delete')) {
		$args = [];
		premises_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='premises' AND `pkValue`='{$selected_id}'", $eo);
}

function premises_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('premises', $selected_id, 'edit')) return false;

	$data = [
		'premises_name' => Request::val('premises_name', ''),
		'premises_latitude' => Request::val('premises_latitude', ''),
		'premises_longitude' => Request::val('premises_longitude', ''),
		'premises_radius' => Request::val('premises_radius', ''),
		'premises_opening' => Request::lookup('premises_opening', ''),
		'premises_closing' => Request::lookup('premises_closing', ''),
		'premises_updated' => parseCode('<%%editingTimestamp%%>', false, true),
	];

	if($data['premises_name'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Premise Name': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['premises_latitude'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Latitude': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['premises_longitude'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Longitude': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['premises_radius'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Premises radius': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('premises', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: premises_before_update
	if(function_exists('premises_before_update')) {
		$args = ['old_data' => $old_data];
		if(!premises_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'premises',
		backtick_keys_once($set),
		['`premises_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="premises_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('premises', $data['selectedID'], calculated_fields()['premises']);

	// hook: premises_after_update
	if(function_exists('premises_after_update')) {
		if($row = getRecord('premises', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['premises_id'];
		$args = ['old_data' => $old_data];
		if(!premises_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('premises', $selected_id);
}

function premises_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('premises');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('premises', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('premises', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('premises', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_premises_opening = Request::val('filterer_premises_opening');
	$filterer_premises_closing = Request::val('filterer_premises_closing');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: premises_opening
	$combo_premises_opening = new DataCombo;
	// combobox: premises_closing
	$combo_premises_closing = new DataCombo;

	if($hasSelectedId) {
		if(!($row = getRecord('premises', $selectedId))) {
			return error_message($Translation['No records found'], 'premises_view.php', false);
		}
		$combo_premises_opening->SelectedData = $row['premises_opening'];
		$combo_premises_closing->SelectedData = $row['premises_closing'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_premises_opening->SelectedData = $filterer_premises_opening;
		$combo_premises_closing->SelectedData = $filterer_premises_closing;
	}
	$combo_premises_opening->HTML = '<span id="premises_opening-container' . $rnd1 . '"></span><input type="hidden" name="premises_opening" id="premises_opening' . $rnd1 . '" value="' . html_attr($combo_premises_opening->SelectedData) . '">';
	$combo_premises_opening->MatchText = '<span id="premises_opening-container-readonly' . $rnd1 . '"></span><input type="hidden" name="premises_opening" id="premises_opening' . $rnd1 . '" value="' . html_attr($combo_premises_opening->SelectedData) . '">';
	$combo_premises_closing->HTML = '<span id="premises_closing-container' . $rnd1 . '"></span><input type="hidden" name="premises_closing" id="premises_closing' . $rnd1 . '" value="' . html_attr($combo_premises_closing->SelectedData) . '">';
	$combo_premises_closing->MatchText = '<span id="premises_closing-container-readonly' . $rnd1 . '"></span><input type="hidden" name="premises_closing" id="premises_closing' . $rnd1 . '" value="' . html_attr($combo_premises_closing->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_premises_opening__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['premises_opening'] : htmlspecialchars($filterer_premises_opening, ENT_QUOTES)); ?>"};
		AppGini.current_premises_closing__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['premises_closing'] : htmlspecialchars($filterer_premises_closing, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(premises_opening_reload__RAND__) == 'function') premises_opening_reload__RAND__();
				if(typeof(premises_closing_reload__RAND__) == 'function') premises_closing_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function premises_opening_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#premises_opening-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_premises_opening__RAND__.value, t: 'premises', f: 'premises_opening' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="premises_opening"]').val(resp.results[0].id);
							$j('[id=premises_opening-container-readonly__RAND__]').html('<span class="match-text" id="premises_opening-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whens_view_parent]').hide(); } else { $j('.btn[id=whens_view_parent]').show(); }


							if(typeof(premises_opening_update_autofills__RAND__) == 'function') premises_opening_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'premises', f: 'premises_opening' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_premises_opening__RAND__.value = e.added.id;
				AppGini.current_premises_opening__RAND__.text = e.added.text;
				$j('[name="premises_opening"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=whens_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(premises_opening_update_autofills__RAND__) == 'function') premises_opening_update_autofills__RAND__();
			});

			if(!$j("#premises_opening-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_premises_opening__RAND__.value, t: 'premises', f: 'premises_opening' },
					success: function(resp) {
						$j('[name="premises_opening"]').val(resp.results[0].id);
						$j('[id=premises_opening-container-readonly__RAND__]').html('<span class="match-text" id="premises_opening-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whens_view_parent]').hide(); } else { $j('.btn[id=whens_view_parent]').show(); }

						if(typeof(premises_opening_update_autofills__RAND__) == 'function') premises_opening_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_premises_opening__RAND__.value, t: 'premises', f: 'premises_opening' },
				success: function(resp) {
					$j('[id=premises_opening-container__RAND__], [id=premises_opening-container-readonly__RAND__]').html('<span class="match-text" id="premises_opening-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whens_view_parent]').hide(); } else { $j('.btn[id=whens_view_parent]').show(); }

					if(typeof(premises_opening_update_autofills__RAND__) == 'function') premises_opening_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function premises_closing_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#premises_closing-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_premises_closing__RAND__.value, t: 'premises', f: 'premises_closing' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="premises_closing"]').val(resp.results[0].id);
							$j('[id=premises_closing-container-readonly__RAND__]').html('<span class="match-text" id="premises_closing-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whens_view_parent]').hide(); } else { $j('.btn[id=whens_view_parent]').show(); }


							if(typeof(premises_closing_update_autofills__RAND__) == 'function') premises_closing_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'premises', f: 'premises_closing' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_premises_closing__RAND__.value = e.added.id;
				AppGini.current_premises_closing__RAND__.text = e.added.text;
				$j('[name="premises_closing"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=whens_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(premises_closing_update_autofills__RAND__) == 'function') premises_closing_update_autofills__RAND__();
			});

			if(!$j("#premises_closing-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_premises_closing__RAND__.value, t: 'premises', f: 'premises_closing' },
					success: function(resp) {
						$j('[name="premises_closing"]').val(resp.results[0].id);
						$j('[id=premises_closing-container-readonly__RAND__]').html('<span class="match-text" id="premises_closing-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whens_view_parent]').hide(); } else { $j('.btn[id=whens_view_parent]').show(); }

						if(typeof(premises_closing_update_autofills__RAND__) == 'function') premises_closing_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_premises_closing__RAND__.value, t: 'premises', f: 'premises_closing' },
				success: function(resp) {
					$j('[id=premises_closing-container__RAND__], [id=premises_closing-container-readonly__RAND__]').html('<span class="match-text" id="premises_closing-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=whens_view_parent]').hide(); } else { $j('.btn[id=whens_view_parent]').show(); }

					if(typeof(premises_closing_update_autofills__RAND__) == 'function') premises_closing_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/premises_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/premises_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Premise details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#premises_name').replaceWith('<div class=\"form-control-static\" id=\"premises_name\">' + (\$j('#premises_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#premises_latitude').replaceWith('<div class=\"form-control-static\" id=\"premises_latitude\">' + (\$j('#premises_latitude').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#premises_longitude').replaceWith('<div class=\"form-control-static\" id=\"premises_longitude\">' + (\$j('#premises_longitude').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#premises_radius').replaceWith('<div class=\"form-control-static\" id=\"premises_radius\">' + (\$j('#premises_radius').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#premises_opening').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#premises_opening_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#premises_closing').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#premises_closing_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(premises_opening)%%>', $combo_premises_opening->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(premises_opening)%%>', $combo_premises_opening->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(premises_opening)%%>', urlencode($combo_premises_opening->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(premises_closing)%%>', $combo_premises_closing->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(premises_closing)%%>', $combo_premises_closing->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(premises_closing)%%>', urlencode($combo_premises_closing->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['premises_opening' => ['whens', 'Premises Opening'], 'premises_closing' => ['whens', 'Premises Closing'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(premises_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_latitude)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_longitude)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_radius)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_opening)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_closing)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_created)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(premises_updated)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(premises_id)%%>', safe_html($urow['premises_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(premises_id)%%>', html_attr($row['premises_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_id)%%>', urlencode($urow['premises_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(premises_name)%%>', safe_html($urow['premises_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(premises_name)%%>', html_attr($row['premises_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_name)%%>', urlencode($urow['premises_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(premises_latitude)%%>', safe_html($urow['premises_latitude']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(premises_latitude)%%>', html_attr($row['premises_latitude']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_latitude)%%>', urlencode($urow['premises_latitude']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(premises_longitude)%%>', safe_html($urow['premises_longitude']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(premises_longitude)%%>', html_attr($row['premises_longitude']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_longitude)%%>', urlencode($urow['premises_longitude']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(premises_radius)%%>', safe_html($urow['premises_radius']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(premises_radius)%%>', html_attr($row['premises_radius']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_radius)%%>', urlencode($urow['premises_radius']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(premises_opening)%%>', safe_html($urow['premises_opening']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(premises_opening)%%>', html_attr($row['premises_opening']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_opening)%%>', urlencode($urow['premises_opening']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(premises_closing)%%>', safe_html($urow['premises_closing']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(premises_closing)%%>', html_attr($row['premises_closing']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_closing)%%>', urlencode($urow['premises_closing']), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_created)%%>', safe_html($urow['premises_created']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_created)%%>', urlencode($urow['premises_created']), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_updated)%%>', safe_html($urow['premises_updated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_updated)%%>', urlencode($urow['premises_updated']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(premises_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_latitude)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_latitude)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_longitude)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_longitude)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_radius)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_radius)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_opening)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_opening)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_closing)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_closing)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_created)%%>', '<%%creationTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_created)%%>', urlencode('<%%creationTimestamp%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(premises_updated)%%>', '<%%editingTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(premises_updated)%%>', urlencode('<%%editingTimestamp%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('premises');
	if($hasSelectedId) {
		$jdata = get_joined_record('premises', $selectedId);
		if($jdata === false) $jdata = get_defaults('premises');
		$rdata = $row;
	}
	$templateCode .= loadView('premises-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: premises_dv
	if(function_exists('premises_dv')) {
		$args = [];
		premises_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}