<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/premises.php');
	include_once(__DIR__ . '/premises_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('premises');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'premises';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`premises`.`premises_id`" => "premises_id",
		"`premises`.`premises_name`" => "premises_name",
		"`premises`.`premises_latitude`" => "premises_latitude",
		"`premises`.`premises_longitude`" => "premises_longitude",
		"`premises`.`premises_radius`" => "premises_radius",
		"`premises`.`premises_created`" => "premises_created",
		"`premises`.`premises_updated`" => "premises_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`premises`.`premises_id`',
		2 => 2,
		3 => '`premises`.`premises_latitude`',
		4 => '`premises`.`premises_longitude`',
		5 => '`premises`.`premises_radius`',
		6 => '`premises`.`premises_created`',
		7 => '`premises`.`premises_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`premises`.`premises_id`" => "premises_id",
		"`premises`.`premises_name`" => "premises_name",
		"`premises`.`premises_latitude`" => "premises_latitude",
		"`premises`.`premises_longitude`" => "premises_longitude",
		"`premises`.`premises_radius`" => "premises_radius",
		"`premises`.`premises_created`" => "premises_created",
		"`premises`.`premises_updated`" => "premises_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`premises`.`premises_id`" => "Id",
		"`premises`.`premises_name`" => "Premise Name",
		"`premises`.`premises_latitude`" => "Latitude",
		"`premises`.`premises_longitude`" => "Longitude",
		"`premises`.`premises_radius`" => "Premises radius",
		"`premises`.`premises_created`" => "Premises created",
		"`premises`.`premises_updated`" => "Premises updated",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`premises`.`premises_id`" => "premises_id",
		"`premises`.`premises_name`" => "premises_name",
		"`premises`.`premises_latitude`" => "premises_latitude",
		"`premises`.`premises_longitude`" => "premises_longitude",
		"`premises`.`premises_radius`" => "premises_radius",
		"`premises`.`premises_created`" => "premises_created",
		"`premises`.`premises_updated`" => "premises_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`premises` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'premises_view.php';
	$x->TableTitle = 'Premises';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`premises`.`premises_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 100, ];
	$x->ColCaption = ['Id', 'Premise Name', 'Latitude', 'Longitude', 'Premises radius', 'Premises created', 'Premises updated', 'Pnb', ];
	$x->ColFieldName = ['premises_id', 'premises_name', 'premises_latitude', 'premises_longitude', 'premises_radius', 'premises_created', 'premises_updated', '%pnb.pnb_premises_id%', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, -1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/premises_templateTV.html';
	$x->SelectedTemplate = 'templates/premises_templateTVS.html';
	$x->TemplateDV = 'templates/premises_templateDV.html';
	$x->TemplateDVP = 'templates/premises_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: premises_init
	$render = true;
	if(function_exists('premises_init')) {
		$args = [];
		$render = premises_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: premises_header
	$headerCode = '';
	if(function_exists('premises_header')) {
		$args = [];
		$headerCode = premises_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: premises_footer
	$footerCode = '';
	if(function_exists('premises_footer')) {
		$args = [];
		$footerCode = premises_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
