<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/utedb.php');
	include_once(__DIR__ . '/utedb_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('utedb');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'utedb';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`utedb`.`utedb_id`" => "utedb_id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "utedb_madb",
		"`utedb`.`utedb_madb_who1`" => "utedb_madb_who1",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "utedb_premises_id",
		"`utedb`.`utedb_proof_image`" => "utedb_proof_image",
		"`utedb`.`utedb_ai_audit`" => "utedb_ai_audit",
		"`utedb`.`utedb_pc_audit`" => "utedb_pc_audit",
		"`utedb`.`utedb_rda_audit`" => "utedb_rda_audit",
		"`utedb`.`utedb_bb_audit`" => "utedb_bb_audit",
		"`utedb`.`utedb_car`" => "utedb_car",
		"`utedb`.`utedb_car_vid`" => "utedb_car_vid",
		"`utedb`.`utedb_col_tf`" => "utedb_col_tf",
		"`utedb`.`utedb_delta_flag`" => "utedb_delta_flag",
		"`utedb`.`utedb_hows1`" => "utedb_hows1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* ELAI RDA ID */" => "utedb_elairda_id",
		"`utedb`.`utedb_created`" => "utedb_created",
		"`utedb`.`utedb_updated`" => "utedb_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`utedb`.`utedb_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`utedb`.`utedb_ai_audit`',
		7 => 7,
		8 => 8,
		9 => 9,
		10 => '`utedb`.`utedb_car`',
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => '`utedb`.`utedb_created`',
		17 => '`utedb`.`utedb_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`utedb`.`utedb_id`" => "utedb_id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "utedb_madb",
		"`utedb`.`utedb_madb_who1`" => "utedb_madb_who1",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "utedb_premises_id",
		"`utedb`.`utedb_proof_image`" => "utedb_proof_image",
		"`utedb`.`utedb_ai_audit`" => "utedb_ai_audit",
		"`utedb`.`utedb_pc_audit`" => "utedb_pc_audit",
		"`utedb`.`utedb_rda_audit`" => "utedb_rda_audit",
		"`utedb`.`utedb_bb_audit`" => "utedb_bb_audit",
		"`utedb`.`utedb_car`" => "utedb_car",
		"`utedb`.`utedb_car_vid`" => "utedb_car_vid",
		"`utedb`.`utedb_col_tf`" => "utedb_col_tf",
		"`utedb`.`utedb_delta_flag`" => "utedb_delta_flag",
		"`utedb`.`utedb_hows1`" => "utedb_hows1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* ELAI RDA ID */" => "utedb_elairda_id",
		"`utedb`.`utedb_created`" => "utedb_created",
		"`utedb`.`utedb_updated`" => "utedb_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`utedb`.`utedb_id`" => "Utedb id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "MADb Id",
		"`utedb`.`utedb_madb_who1`" => "Who 1",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "Premises Id",
		"`utedb`.`utedb_ai_audit`" => "AI Audit (%) Score",
		"`utedb`.`utedb_pc_audit`" => "PC Audit",
		"`utedb`.`utedb_rda_audit`" => "RDA Audit",
		"`utedb`.`utedb_bb_audit`" => "BB Audit",
		"`utedb`.`utedb_car`" => "Customer Review(s)",
		"`utedb`.`utedb_car_vid`" => "CAR VIDEO",
		"`utedb`.`utedb_col_tf`" => "Collective TF",
		"`utedb`.`utedb_delta_flag`" => "Delta Flag",
		"`utedb`.`utedb_hows1`" => "Hows Score",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* ELAI RDA ID */" => "ELAI RDA ID",
		"`utedb`.`utedb_created`" => "Created AT",
		"`utedb`.`utedb_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`utedb`.`utedb_id`" => "utedb_id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "utedb_madb",
		"`utedb`.`utedb_madb_who1`" => "utedb_madb_who1",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "utedb_premises_id",
		"`utedb`.`utedb_ai_audit`" => "utedb_ai_audit",
		"`utedb`.`utedb_pc_audit`" => "utedb_pc_audit",
		"`utedb`.`utedb_rda_audit`" => "utedb_rda_audit",
		"`utedb`.`utedb_bb_audit`" => "utedb_bb_audit",
		"`utedb`.`utedb_car`" => "utedb_car",
		"`utedb`.`utedb_car_vid`" => "utedb_car_vid",
		"`utedb`.`utedb_col_tf`" => "utedb_col_tf",
		"`utedb`.`utedb_delta_flag`" => "utedb_delta_flag",
		"`utedb`.`utedb_hows1`" => "utedb_hows1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* ELAI RDA ID */" => "utedb_elairda_id",
		"`utedb`.`utedb_created`" => "utedb_created",
		"`utedb`.`utedb_updated`" => "utedb_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['utedb_madb' => 'MADb Id', 'utedb_elairda_id' => 'ELAI RDA ID', ];

	$x->QueryFrom = "`utedb` LEFT JOIN `madb` as madb1 ON `madb1`.`madb_id`=`utedb`.`utedb_madb` LEFT JOIN `whats` as whats1 ON `whats1`.`whats_id`=`madb1`.`madb_what1` LEFT JOIN `whos` as whos1 ON `whos1`.`whos_id`=`utedb`.`utedb_elairda_id` LEFT JOIN `premises` as premises1 ON `premises1`.`premises_id`=`madb1`.`madb_premises_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 500;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'utedb_view.php';
	$x->TableTitle = 'Universal TEDB';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`utedb`.`utedb_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Utedb id', 'MADb Id', 'Who 1', 'Premises Id', 'Utedb proof image', 'AI Audit (%) Score', 'PC Audit', 'RDA Audit', 'BB Audit', 'Customer Review(s)', 'CAR VIDEO', 'Collective TF', 'Delta Flag', 'Hows Score', 'ELAI RDA ID', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['utedb_id', 'utedb_madb', 'utedb_madb_who1', 'utedb_premises_id', 'utedb_proof_image', 'utedb_ai_audit', 'utedb_pc_audit', 'utedb_rda_audit', 'utedb_bb_audit', 'utedb_car', 'utedb_car_vid', 'utedb_col_tf', 'utedb_delta_flag', 'utedb_hows1', 'utedb_elairda_id', 'utedb_created', 'utedb_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/utedb_templateTV.html';
	$x->SelectedTemplate = 'templates/utedb_templateTVS.html';
	$x->TemplateDV = 'templates/utedb_templateDV.html';
	$x->TemplateDVP = 'templates/utedb_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: utedb_init
	$render = true;
	if(function_exists('utedb_init')) {
		$args = [];
		$render = utedb_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: utedb_header
	$headerCode = '';
	if(function_exists('utedb_header')) {
		$args = [];
		$headerCode = utedb_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: utedb_footer
	$footerCode = '';
	if(function_exists('utedb_footer')) {
		$args = [];
		$footerCode = utedb_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
