<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/utedb.php');
	include_once(__DIR__ . '/utedb_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('utedb');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'utedb';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`utedb`.`utedb_id`" => "utedb_id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "utedb_madb",
		"IF(    CHAR_LENGTH(`whats2`.`whats_what1`), CONCAT_WS('',   `whats2`.`whats_what1`), '') /* What 1 */" => "utedb_what1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who 1 */" => "utedb_who1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`) || CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   `whens1`.`whens_when2`, '-', if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 1 */" => "utedb_when1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which 1 */" => "utedb_which1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where 1 */" => "utedb_where1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why 1 */" => "utedb_why1",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr1`) || CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr1`, '-', `howrs1`.`howrs_howr2`), '') /* How (R) 1 */" => "utedb_howr1",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows1`) || CHAR_LENGTH(`howss1`.`howss_hows2`), CONCAT_WS('',   `howss1`.`howss_hows1`, '-', `howss1`.`howss_hows2`), '') /* How (S) 1 */" => "utedb_hows1",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq1`) || CHAR_LENGTH(`howqs1`.`howqs_howq2`), CONCAT_WS('',   `howqs1`.`howqs_howq1`, '-', `howqs1`.`howqs_howq2`), '') /* How (Q) 1 */" => "utedb_howq1",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt1`) || CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt1`, '-', `howts1`.`howts_howt2`), '') /* How (T) 1 */" => "utedb_howt1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why 2 */" => "utedb_why2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why 3 */" => "utedb_why3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where 2 */" => "utedb_where2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where 3 */" => "utedb_where3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which 2 */" => "utedb_which2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which 3 */" => "utedb_which3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When 2 */" => "utedb_when2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 3 */" => "utedb_when3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who 2 */" => "utedb_who2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who 3 */" => "utedb_who3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What 2 */" => "utedb_what2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What 3 */" => "utedb_what3",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr2`), '') /* How (R) 2 */" => "utedb_howr2",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr3`), CONCAT_WS('',   `howrs1`.`howrs_howr3`), '') /* How (R) 3 */" => "utedb_howr3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (S) 2 */" => "utedb_hows2",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows3`), CONCAT_WS('',   `howss1`.`howss_hows3`), '') /* How (S) 3 */" => "utedb_hows3",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq3`), CONCAT_WS('',   `howqs1`.`howqs_howq3`), '') /* How (Q) 2 */" => "utedb_howq2",
		"IF(    CHAR_LENGTH(`howqs3`.`howqs_howq1`) || CHAR_LENGTH(`howqs3`.`howqs_howq2`), CONCAT_WS('',   `howqs3`.`howqs_howq1`, '-', `howqs3`.`howqs_howq2`), '') /* How (Q) 3 */" => "utedb_howq3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (T) 2 */" => "utedb_howt2",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt3`), CONCAT_WS('',   `howts1`.`howts_howt3`), '') /* How (T) 3 */" => "utedb_howt3",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "utedb_premises_id",
		"`utedb`.`utedb_proof_image`" => "utedb_proof_image",
		"`utedb`.`utedb_ai_audit`" => "utedb_ai_audit",
		"`utedb`.`utedb_pc_audit`" => "utedb_pc_audit",
		"`utedb`.`utedb_rda_audit`" => "utedb_rda_audit",
		"`utedb`.`utedb_bb_audit`" => "utedb_bb_audit",
		"`utedb`.`utedb_car`" => "utedb_car",
		"`utedb`.`utedb_car_vid`" => "utedb_car_vid",
		"`utedb`.`utedb_col_tf`" => "utedb_col_tf",
		"`utedb`.`utedb_delta_flag`" => "utedb_delta_flag",
		"`utedb`.`utedb_created`" => "utedb_created",
		"`utedb`.`utedb_updated`" => "utedb_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`utedb`.`utedb_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => 28,
		29 => 29,
		30 => 30,
		31 => 31,
		32 => 32,
		33 => 33,
		34 => 34,
		35 => '`utedb`.`utedb_ai_audit`',
		36 => 36,
		37 => 37,
		38 => 38,
		39 => '`utedb`.`utedb_car`',
		40 => 40,
		41 => 41,
		42 => 42,
		43 => '`utedb`.`utedb_created`',
		44 => '`utedb`.`utedb_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`utedb`.`utedb_id`" => "utedb_id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "utedb_madb",
		"IF(    CHAR_LENGTH(`whats2`.`whats_what1`), CONCAT_WS('',   `whats2`.`whats_what1`), '') /* What 1 */" => "utedb_what1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who 1 */" => "utedb_who1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`) || CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   `whens1`.`whens_when2`, '-', if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 1 */" => "utedb_when1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which 1 */" => "utedb_which1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where 1 */" => "utedb_where1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why 1 */" => "utedb_why1",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr1`) || CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr1`, '-', `howrs1`.`howrs_howr2`), '') /* How (R) 1 */" => "utedb_howr1",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows1`) || CHAR_LENGTH(`howss1`.`howss_hows2`), CONCAT_WS('',   `howss1`.`howss_hows1`, '-', `howss1`.`howss_hows2`), '') /* How (S) 1 */" => "utedb_hows1",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq1`) || CHAR_LENGTH(`howqs1`.`howqs_howq2`), CONCAT_WS('',   `howqs1`.`howqs_howq1`, '-', `howqs1`.`howqs_howq2`), '') /* How (Q) 1 */" => "utedb_howq1",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt1`) || CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt1`, '-', `howts1`.`howts_howt2`), '') /* How (T) 1 */" => "utedb_howt1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why 2 */" => "utedb_why2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why 3 */" => "utedb_why3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where 2 */" => "utedb_where2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where 3 */" => "utedb_where3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which 2 */" => "utedb_which2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which 3 */" => "utedb_which3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When 2 */" => "utedb_when2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 3 */" => "utedb_when3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who 2 */" => "utedb_who2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who 3 */" => "utedb_who3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What 2 */" => "utedb_what2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What 3 */" => "utedb_what3",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr2`), '') /* How (R) 2 */" => "utedb_howr2",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr3`), CONCAT_WS('',   `howrs1`.`howrs_howr3`), '') /* How (R) 3 */" => "utedb_howr3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (S) 2 */" => "utedb_hows2",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows3`), CONCAT_WS('',   `howss1`.`howss_hows3`), '') /* How (S) 3 */" => "utedb_hows3",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq3`), CONCAT_WS('',   `howqs1`.`howqs_howq3`), '') /* How (Q) 2 */" => "utedb_howq2",
		"IF(    CHAR_LENGTH(`howqs3`.`howqs_howq1`) || CHAR_LENGTH(`howqs3`.`howqs_howq2`), CONCAT_WS('',   `howqs3`.`howqs_howq1`, '-', `howqs3`.`howqs_howq2`), '') /* How (Q) 3 */" => "utedb_howq3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (T) 2 */" => "utedb_howt2",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt3`), CONCAT_WS('',   `howts1`.`howts_howt3`), '') /* How (T) 3 */" => "utedb_howt3",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "utedb_premises_id",
		"`utedb`.`utedb_proof_image`" => "utedb_proof_image",
		"`utedb`.`utedb_ai_audit`" => "utedb_ai_audit",
		"`utedb`.`utedb_pc_audit`" => "utedb_pc_audit",
		"`utedb`.`utedb_rda_audit`" => "utedb_rda_audit",
		"`utedb`.`utedb_bb_audit`" => "utedb_bb_audit",
		"`utedb`.`utedb_car`" => "utedb_car",
		"`utedb`.`utedb_car_vid`" => "utedb_car_vid",
		"`utedb`.`utedb_col_tf`" => "utedb_col_tf",
		"`utedb`.`utedb_delta_flag`" => "utedb_delta_flag",
		"`utedb`.`utedb_created`" => "utedb_created",
		"`utedb`.`utedb_updated`" => "utedb_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`utedb`.`utedb_id`" => "Utedb id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "MADb Id",
		"IF(    CHAR_LENGTH(`whats2`.`whats_what1`), CONCAT_WS('',   `whats2`.`whats_what1`), '') /* What 1 */" => "What 1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who 1 */" => "Who 1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`) || CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   `whens1`.`whens_when2`, '-', if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 1 */" => "When 1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which 1 */" => "Which 1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where 1 */" => "Where 1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why 1 */" => "Why 1",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr1`) || CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr1`, '-', `howrs1`.`howrs_howr2`), '') /* How (R) 1 */" => "How (R) 1",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows1`) || CHAR_LENGTH(`howss1`.`howss_hows2`), CONCAT_WS('',   `howss1`.`howss_hows1`, '-', `howss1`.`howss_hows2`), '') /* How (S) 1 */" => "How (S) 1",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq1`) || CHAR_LENGTH(`howqs1`.`howqs_howq2`), CONCAT_WS('',   `howqs1`.`howqs_howq1`, '-', `howqs1`.`howqs_howq2`), '') /* How (Q) 1 */" => "How (Q) 1",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt1`) || CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt1`, '-', `howts1`.`howts_howt2`), '') /* How (T) 1 */" => "How (T) 1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why 2 */" => "Why 2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why 3 */" => "Why 3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where 2 */" => "Where 2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where 3 */" => "Where 3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which 2 */" => "Which 2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which 3 */" => "Which 3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When 2 */" => "When 2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 3 */" => "When 3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who 2 */" => "Who 2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who 3 */" => "Who 3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What 2 */" => "What 2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What 3 */" => "What 3",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr2`), '') /* How (R) 2 */" => "How (R) 2",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr3`), CONCAT_WS('',   `howrs1`.`howrs_howr3`), '') /* How (R) 3 */" => "How (R) 3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (S) 2 */" => "How (S) 2",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows3`), CONCAT_WS('',   `howss1`.`howss_hows3`), '') /* How (S) 3 */" => "How (S) 3",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq3`), CONCAT_WS('',   `howqs1`.`howqs_howq3`), '') /* How (Q) 2 */" => "How (Q) 2",
		"IF(    CHAR_LENGTH(`howqs3`.`howqs_howq1`) || CHAR_LENGTH(`howqs3`.`howqs_howq2`), CONCAT_WS('',   `howqs3`.`howqs_howq1`, '-', `howqs3`.`howqs_howq2`), '') /* How (Q) 3 */" => "How (Q) 3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (T) 2 */" => "How (T) 2",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt3`), CONCAT_WS('',   `howts1`.`howts_howt3`), '') /* How (T) 3 */" => "How (T) 3",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "Premises Id",
		"`utedb`.`utedb_ai_audit`" => "AI Audit (%) Score",
		"`utedb`.`utedb_pc_audit`" => "PC Audit",
		"`utedb`.`utedb_rda_audit`" => "RDA Audit",
		"`utedb`.`utedb_bb_audit`" => "BB Audit",
		"`utedb`.`utedb_car`" => "Customer Review(s)",
		"`utedb`.`utedb_car_vid`" => "CAR VIDEO",
		"`utedb`.`utedb_col_tf`" => "Col. TF",
		"`utedb`.`utedb_delta_flag`" => "Delta Flag",
		"`utedb`.`utedb_created`" => "Created AT",
		"`utedb`.`utedb_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`utedb`.`utedb_id`" => "utedb_id",
		"IF(    CHAR_LENGTH(`madb1`.`madb_id`) || CHAR_LENGTH(`whats1`.`whats_what1`), CONCAT_WS('',   `madb1`.`madb_id`, '-', `whats1`.`whats_what1`), '') /* MADb Id */" => "utedb_madb",
		"IF(    CHAR_LENGTH(`whats2`.`whats_what1`), CONCAT_WS('',   `whats2`.`whats_what1`), '') /* What 1 */" => "utedb_what1",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who1`) || CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who1`, '-', `whos1`.`whos_who2`), '') /* Who 1 */" => "utedb_who1",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`) || CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   `whens1`.`whens_when2`, '-', if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 1 */" => "utedb_when1",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which1`) || CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which1`, '-', `whichs1`.`whichs_which2`), '') /* Which 1 */" => "utedb_which1",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where1`) || CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where1`, '-', `wheres1`.`wheres_where2`), '') /* Where 1 */" => "utedb_where1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why1`) || CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why1`, '-', `whys1`.`whys_why2`), '') /* Why 1 */" => "utedb_why1",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr1`) || CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr1`, '-', `howrs1`.`howrs_howr2`), '') /* How (R) 1 */" => "utedb_howr1",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows1`) || CHAR_LENGTH(`howss1`.`howss_hows2`), CONCAT_WS('',   `howss1`.`howss_hows1`, '-', `howss1`.`howss_hows2`), '') /* How (S) 1 */" => "utedb_hows1",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq1`) || CHAR_LENGTH(`howqs1`.`howqs_howq2`), CONCAT_WS('',   `howqs1`.`howqs_howq1`, '-', `howqs1`.`howqs_howq2`), '') /* How (Q) 1 */" => "utedb_howq1",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt1`) || CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt1`, '-', `howts1`.`howts_howt2`), '') /* How (T) 1 */" => "utedb_howt1",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why2`), CONCAT_WS('',   `whys1`.`whys_why2`), '') /* Why 2 */" => "utedb_why2",
		"IF(    CHAR_LENGTH(`whys1`.`whys_why3`), CONCAT_WS('',   `whys1`.`whys_why3`), '') /* Why 3 */" => "utedb_why3",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where2`), CONCAT_WS('',   `wheres1`.`wheres_where2`), '') /* Where 2 */" => "utedb_where2",
		"IF(    CHAR_LENGTH(`wheres1`.`wheres_where3`), CONCAT_WS('',   `wheres1`.`wheres_where3`), '') /* Where 3 */" => "utedb_where3",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which2`), CONCAT_WS('',   `whichs1`.`whichs_which2`), '') /* Which 2 */" => "utedb_which2",
		"IF(    CHAR_LENGTH(`whichs1`.`whichs_which3`), CONCAT_WS('',   `whichs1`.`whichs_which3`), '') /* Which 3 */" => "utedb_which3",
		"IF(    CHAR_LENGTH(`whens1`.`whens_when2`), CONCAT_WS('',   `whens1`.`whens_when2`), '') /* When 2 */" => "utedb_when2",
		"IF(    CHAR_LENGTH(if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), CONCAT_WS('',   if(`whens1`.`whens_when3`,time_format(`whens1`.`whens_when3`,'%r'),'')), '') /* When 3 */" => "utedb_when3",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who2`), CONCAT_WS('',   `whos1`.`whos_who2`), '') /* Who 2 */" => "utedb_who2",
		"IF(    CHAR_LENGTH(`whos1`.`whos_who3`), CONCAT_WS('',   `whos1`.`whos_who3`), '') /* Who 3 */" => "utedb_who3",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what2`), CONCAT_WS('',   `whats1`.`whats_what2`), '') /* What 2 */" => "utedb_what2",
		"IF(    CHAR_LENGTH(`whats1`.`whats_what3`), CONCAT_WS('',   `whats1`.`whats_what3`), '') /* What 3 */" => "utedb_what3",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr2`), CONCAT_WS('',   `howrs1`.`howrs_howr2`), '') /* How (R) 2 */" => "utedb_howr2",
		"IF(    CHAR_LENGTH(`howrs1`.`howrs_howr3`), CONCAT_WS('',   `howrs1`.`howrs_howr3`), '') /* How (R) 3 */" => "utedb_howr3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (S) 2 */" => "utedb_hows2",
		"IF(    CHAR_LENGTH(`howss1`.`howss_hows3`), CONCAT_WS('',   `howss1`.`howss_hows3`), '') /* How (S) 3 */" => "utedb_hows3",
		"IF(    CHAR_LENGTH(`howqs1`.`howqs_howq3`), CONCAT_WS('',   `howqs1`.`howqs_howq3`), '') /* How (Q) 2 */" => "utedb_howq2",
		"IF(    CHAR_LENGTH(`howqs3`.`howqs_howq1`) || CHAR_LENGTH(`howqs3`.`howqs_howq2`), CONCAT_WS('',   `howqs3`.`howqs_howq1`, '-', `howqs3`.`howqs_howq2`), '') /* How (Q) 3 */" => "utedb_howq3",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt2`), CONCAT_WS('',   `howts1`.`howts_howt2`), '') /* How (T) 2 */" => "utedb_howt2",
		"IF(    CHAR_LENGTH(`howts1`.`howts_howt3`), CONCAT_WS('',   `howts1`.`howts_howt3`), '') /* How (T) 3 */" => "utedb_howt3",
		"IF(    CHAR_LENGTH(`premises1`.`premises_id`) || CHAR_LENGTH(`premises1`.`premises_name`), CONCAT_WS('',   `premises1`.`premises_id`, '-', `premises1`.`premises_name`), '') /* Premises Id */" => "utedb_premises_id",
		"`utedb`.`utedb_ai_audit`" => "utedb_ai_audit",
		"`utedb`.`utedb_pc_audit`" => "utedb_pc_audit",
		"`utedb`.`utedb_rda_audit`" => "utedb_rda_audit",
		"`utedb`.`utedb_bb_audit`" => "utedb_bb_audit",
		"`utedb`.`utedb_car`" => "utedb_car",
		"`utedb`.`utedb_car_vid`" => "utedb_car_vid",
		"`utedb`.`utedb_col_tf`" => "utedb_col_tf",
		"`utedb`.`utedb_delta_flag`" => "utedb_delta_flag",
		"`utedb`.`utedb_created`" => "utedb_created",
		"`utedb`.`utedb_updated`" => "utedb_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['utedb_madb' => 'MADb Id', ];

	$x->QueryFrom = "`utedb` LEFT JOIN `madb` as madb1 ON `madb1`.`madb_id`=`utedb`.`utedb_madb` LEFT JOIN `whats` as whats1 ON `whats1`.`whats_id`=`madb1`.`madb_what1` LEFT JOIN `whats` as whats2 ON `whats2`.`whats_id`=`madb1`.`madb_what1` LEFT JOIN `whos` as whos1 ON `whos1`.`whos_id`=`madb1`.`madb_who1` LEFT JOIN `whens` as whens1 ON `whens1`.`whens_id`=`madb1`.`madb_when1` LEFT JOIN `whichs` as whichs1 ON `whichs1`.`whichs_id`=`madb1`.`madb_which1` LEFT JOIN `wheres` as wheres1 ON `wheres1`.`wheres_id`=`madb1`.`madb_where1` LEFT JOIN `whys` as whys1 ON `whys1`.`whys_id`=`madb1`.`madb_why1` LEFT JOIN `howrs` as howrs1 ON `howrs1`.`howrs_id`=`madb1`.`madb_howr1` LEFT JOIN `howss` as howss1 ON `howss1`.`howss_id`=`madb1`.`madb_hows1` LEFT JOIN `howqs` as howqs1 ON `howqs1`.`howqs_id`=`madb1`.`madb_howq1` LEFT JOIN `howts` as howts1 ON `howts1`.`howts_id`=`madb1`.`madb_howt1` LEFT JOIN `howqs` as howqs3 ON `howqs3`.`howqs_id`=`madb1`.`madb_howq1` LEFT JOIN `premises` as premises1 ON `premises1`.`premises_id`=`madb1`.`madb_premises_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 500;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'utedb_view.php';
	$x->TableTitle = 'Universal TEDB';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`utedb`.`utedb_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Utedb id', 'MADb Id', 'What 1', 'Who 1', 'When 1', 'Which 1', 'Where 1', 'Why 1', 'How (R) 1', 'How (S) 1', 'How (Q) 1', 'How (T) 1', 'Why 2', 'Why 3', 'Where 2', 'Where 3', 'Which 2', 'Which 3', 'When 2', 'When 3', 'Who 2', 'Who 3', 'What 2', 'What 3', 'How (R) 2', 'How (R) 3', 'How (S) 2', 'How (S) 3', 'How (Q) 2', 'How (Q) 3', 'How (T) 2', 'How (T) 3', 'Premises Id', 'Utedb proof image', 'AI Audit (%) Score', 'PC Audit', 'RDA Audit', 'BB Audit', 'Customer Review(s)', 'CAR VIDEO', 'Col. TF', 'Delta Flag', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['utedb_id', 'utedb_madb', 'utedb_what1', 'utedb_who1', 'utedb_when1', 'utedb_which1', 'utedb_where1', 'utedb_why1', 'utedb_howr1', 'utedb_hows1', 'utedb_howq1', 'utedb_howt1', 'utedb_why2', 'utedb_why3', 'utedb_where2', 'utedb_where3', 'utedb_which2', 'utedb_which3', 'utedb_when2', 'utedb_when3', 'utedb_who2', 'utedb_who3', 'utedb_what2', 'utedb_what3', 'utedb_howr2', 'utedb_howr3', 'utedb_hows2', 'utedb_hows3', 'utedb_howq2', 'utedb_howq3', 'utedb_howt2', 'utedb_howt3', 'utedb_premises_id', 'utedb_proof_image', 'utedb_ai_audit', 'utedb_pc_audit', 'utedb_rda_audit', 'utedb_bb_audit', 'utedb_car', 'utedb_car_vid', 'utedb_col_tf', 'utedb_delta_flag', 'utedb_created', 'utedb_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/utedb_templateTV.html';
	$x->SelectedTemplate = 'templates/utedb_templateTVS.html';
	$x->TemplateDV = 'templates/utedb_templateDV.html';
	$x->TemplateDVP = 'templates/utedb_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: utedb_init
	$render = true;
	if(function_exists('utedb_init')) {
		$args = [];
		$render = utedb_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: utedb_header
	$headerCode = '';
	if(function_exists('utedb_header')) {
		$args = [];
		$headerCode = utedb_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: utedb_footer
	$footerCode = '';
	if(function_exists('utedb_footer')) {
		$args = [];
		$footerCode = utedb_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
