<?php

// Data functions (insert, update, delete, form) for table utedb

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function utedb_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('utedb');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'utedb_madb' => Request::lookup('utedb_madb', ''),
		'utedb_what1' => Request::lookup('utedb_madb'),
		'utedb_who1' => Request::lookup('utedb_madb'),
		'utedb_when1' => Request::lookup('utedb_madb'),
		'utedb_which1' => Request::lookup('utedb_madb'),
		'utedb_where1' => Request::lookup('utedb_madb'),
		'utedb_why1' => Request::lookup('utedb_madb'),
		'utedb_howr1' => Request::lookup('utedb_madb'),
		'utedb_hows1' => Request::lookup('utedb_madb'),
		'utedb_howq1' => Request::lookup('utedb_madb'),
		'utedb_howt1' => Request::lookup('utedb_madb'),
		'utedb_why2' => Request::lookup('utedb_madb'),
		'utedb_why3' => Request::lookup('utedb_madb'),
		'utedb_where2' => Request::lookup('utedb_madb'),
		'utedb_where3' => Request::lookup('utedb_madb'),
		'utedb_which2' => Request::lookup('utedb_madb'),
		'utedb_which3' => Request::lookup('utedb_madb'),
		'utedb_when2' => Request::lookup('utedb_madb'),
		'utedb_when3' => Request::lookup('utedb_madb'),
		'utedb_who2' => Request::lookup('utedb_madb'),
		'utedb_who3' => Request::lookup('utedb_madb'),
		'utedb_what2' => Request::lookup('utedb_madb'),
		'utedb_what3' => Request::lookup('utedb_madb'),
		'utedb_howr2' => Request::lookup('utedb_madb'),
		'utedb_howr3' => Request::lookup('utedb_madb'),
		'utedb_hows2' => Request::lookup('utedb_madb'),
		'utedb_hows3' => Request::lookup('utedb_madb'),
		'utedb_howq2' => Request::lookup('utedb_madb'),
		'utedb_howq3' => Request::lookup('utedb_madb'),
		'utedb_howt2' => Request::lookup('utedb_madb'),
		'utedb_howt3' => Request::lookup('utedb_madb'),
		'utedb_premises_id' => Request::lookup('utedb_premises_id', ''),
		'utedb_created' => parseCode('<%%creationTimestamp%%>', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('utedb', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		utedb_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function utedb_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function utedb_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('utedb', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: utedb_before_delete
	if(function_exists('utedb_before_delete')) {
		$args = [];
		if(!utedb_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `utedb` WHERE `utedb_id`='{$selected_id}'", $eo);

	// hook: utedb_after_delete
	if(function_exists('utedb_after_delete')) {
		$args = [];
		utedb_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='utedb' AND `pkValue`='{$selected_id}'", $eo);
}

function utedb_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('utedb', $selected_id, 'edit')) return false;

	$data = [
		'utedb_madb' => Request::lookup('utedb_madb', ''),
		'utedb_what1' => Request::lookup('utedb_madb'),
		'utedb_who1' => Request::lookup('utedb_madb'),
		'utedb_when1' => Request::lookup('utedb_madb'),
		'utedb_which1' => Request::lookup('utedb_madb'),
		'utedb_where1' => Request::lookup('utedb_madb'),
		'utedb_why1' => Request::lookup('utedb_madb'),
		'utedb_howr1' => Request::lookup('utedb_madb'),
		'utedb_hows1' => Request::lookup('utedb_madb'),
		'utedb_howq1' => Request::lookup('utedb_madb'),
		'utedb_howt1' => Request::lookup('utedb_madb'),
		'utedb_why2' => Request::lookup('utedb_madb'),
		'utedb_why3' => Request::lookup('utedb_madb'),
		'utedb_where2' => Request::lookup('utedb_madb'),
		'utedb_where3' => Request::lookup('utedb_madb'),
		'utedb_which2' => Request::lookup('utedb_madb'),
		'utedb_which3' => Request::lookup('utedb_madb'),
		'utedb_when2' => Request::lookup('utedb_madb'),
		'utedb_when3' => Request::lookup('utedb_madb'),
		'utedb_who2' => Request::lookup('utedb_madb'),
		'utedb_who3' => Request::lookup('utedb_madb'),
		'utedb_what2' => Request::lookup('utedb_madb'),
		'utedb_what3' => Request::lookup('utedb_madb'),
		'utedb_howr2' => Request::lookup('utedb_madb'),
		'utedb_howr3' => Request::lookup('utedb_madb'),
		'utedb_hows2' => Request::lookup('utedb_madb'),
		'utedb_hows3' => Request::lookup('utedb_madb'),
		'utedb_howq2' => Request::lookup('utedb_madb'),
		'utedb_howq3' => Request::lookup('utedb_madb'),
		'utedb_howt2' => Request::lookup('utedb_madb'),
		'utedb_howt3' => Request::lookup('utedb_madb'),
		'utedb_premises_id' => Request::lookup('utedb_premises_id', ''),
		'utedb_updated' => parseCode('<%%editingTimestamp%%>', false, true),
	];

	if($data['utedb_madb'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'MADb Id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('utedb', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: utedb_before_update
	if(function_exists('utedb_before_update')) {
		$args = ['old_data' => $old_data];
		if(!utedb_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'utedb',
		backtick_keys_once($set),
		['`utedb_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="utedb_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('utedb', $data['selectedID'], calculated_fields()['utedb']);

	// hook: utedb_after_update
	if(function_exists('utedb_after_update')) {
		if($row = getRecord('utedb', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['utedb_id'];
		$args = ['old_data' => $old_data];
		if(!utedb_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('utedb', $selected_id);
}

function utedb_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('utedb');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('utedb', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('utedb', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('utedb', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_utedb_madb = Request::val('filterer_utedb_madb');
	$filterer_utedb_premises_id = Request::val('filterer_utedb_premises_id');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: utedb_madb
	$combo_utedb_madb = new DataCombo;
	// combobox: utedb_premises_id
	$combo_utedb_premises_id = new DataCombo;

	if($hasSelectedId) {
		if(!($row = getRecord('utedb', $selectedId))) {
			return error_message($Translation['No records found'], 'utedb_view.php', false);
		}
		$combo_utedb_madb->SelectedData = $row['utedb_madb'];
		$combo_utedb_premises_id->SelectedData = $row['utedb_premises_id'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_utedb_madb->SelectedData = $filterer_utedb_madb;
		$combo_utedb_premises_id->SelectedData = $filterer_utedb_premises_id;
	}
	$combo_utedb_madb->HTML = '<span id="utedb_madb-container' . $rnd1 . '"></span><input type="hidden" name="utedb_madb" id="utedb_madb' . $rnd1 . '" value="' . html_attr($combo_utedb_madb->SelectedData) . '">';
	$combo_utedb_madb->MatchText = '<span id="utedb_madb-container-readonly' . $rnd1 . '"></span><input type="hidden" name="utedb_madb" id="utedb_madb' . $rnd1 . '" value="' . html_attr($combo_utedb_madb->SelectedData) . '">';
	$combo_utedb_premises_id->HTML = '<span id="utedb_premises_id-container' . $rnd1 . '"></span><input type="hidden" name="utedb_premises_id" id="utedb_premises_id' . $rnd1 . '" value="' . html_attr($combo_utedb_premises_id->SelectedData) . '">';
	$combo_utedb_premises_id->MatchText = '<span id="utedb_premises_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="utedb_premises_id" id="utedb_premises_id' . $rnd1 . '" value="' . html_attr($combo_utedb_premises_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_utedb_madb__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['utedb_madb'] : htmlspecialchars($filterer_utedb_madb, ENT_QUOTES)); ?>"};
		AppGini.current_utedb_premises_id__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['utedb_premises_id'] : htmlspecialchars($filterer_utedb_premises_id, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(utedb_madb_reload__RAND__) == 'function') utedb_madb_reload__RAND__();
				if(typeof(utedb_premises_id_reload__RAND__) == 'function') utedb_premises_id_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function utedb_madb_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#utedb_madb-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_utedb_madb__RAND__.value, t: 'utedb', f: 'utedb_madb' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="utedb_madb"]').val(resp.results[0].id);
							$j('[id=utedb_madb-container-readonly__RAND__]').html('<span class="match-text" id="utedb_madb-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=madb_view_parent]').hide(); } else { $j('.btn[id=madb_view_parent]').show(); }


							if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'utedb', f: 'utedb_madb' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_utedb_madb__RAND__.value = e.added.id;
				AppGini.current_utedb_madb__RAND__.text = e.added.text;
				$j('[name="utedb_madb"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=madb_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
			});

			if(!$j("#utedb_madb-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_utedb_madb__RAND__.value, t: 'utedb', f: 'utedb_madb' },
					success: function(resp) {
						$j('[name="utedb_madb"]').val(resp.results[0].id);
						$j('[id=utedb_madb-container-readonly__RAND__]').html('<span class="match-text" id="utedb_madb-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=madb_view_parent]').hide(); } else { $j('.btn[id=madb_view_parent]').show(); }

						if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_utedb_madb__RAND__.value, t: 'utedb', f: 'utedb_madb' },
				success: function(resp) {
					$j('[id=utedb_madb-container__RAND__], [id=utedb_madb-container-readonly__RAND__]').html('<span class="match-text" id="utedb_madb-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=madb_view_parent]').hide(); } else { $j('.btn[id=madb_view_parent]').show(); }

					if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function utedb_premises_id_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#utedb_premises_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_utedb_premises_id__RAND__.value, t: 'utedb', f: 'utedb_premises_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="utedb_premises_id"]').val(resp.results[0].id);
							$j('[id=utedb_premises_id-container-readonly__RAND__]').html('<span class="match-text" id="utedb_premises_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=premises_view_parent]').hide(); } else { $j('.btn[id=premises_view_parent]').show(); }


							if(typeof(utedb_premises_id_update_autofills__RAND__) == 'function') utedb_premises_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'utedb', f: 'utedb_premises_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_utedb_premises_id__RAND__.value = e.added.id;
				AppGini.current_utedb_premises_id__RAND__.text = e.added.text;
				$j('[name="utedb_premises_id"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=premises_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(utedb_premises_id_update_autofills__RAND__) == 'function') utedb_premises_id_update_autofills__RAND__();
			});

			if(!$j("#utedb_premises_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_utedb_premises_id__RAND__.value, t: 'utedb', f: 'utedb_premises_id' },
					success: function(resp) {
						$j('[name="utedb_premises_id"]').val(resp.results[0].id);
						$j('[id=utedb_premises_id-container-readonly__RAND__]').html('<span class="match-text" id="utedb_premises_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=premises_view_parent]').hide(); } else { $j('.btn[id=premises_view_parent]').show(); }

						if(typeof(utedb_premises_id_update_autofills__RAND__) == 'function') utedb_premises_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_utedb_premises_id__RAND__.value, t: 'utedb', f: 'utedb_premises_id' },
				success: function(resp) {
					$j('[id=utedb_premises_id-container__RAND__], [id=utedb_premises_id-container-readonly__RAND__]').html('<span class="match-text" id="utedb_premises_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=premises_view_parent]').hide(); } else { $j('.btn[id=premises_view_parent]').show(); }

					if(typeof(utedb_premises_id_update_autofills__RAND__) == 'function') utedb_premises_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/utedb_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/utedb_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Utedb details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#utedb_madb').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#utedb_madb_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#utedb_premises_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#utedb_premises_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(utedb_madb)%%>', $combo_utedb_madb->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_madb)%%>', $combo_utedb_madb->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(utedb_madb)%%>', urlencode($combo_utedb_madb->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(utedb_premises_id)%%>', $combo_utedb_premises_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_premises_id)%%>', $combo_utedb_premises_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(utedb_premises_id)%%>', urlencode($combo_utedb_premises_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['utedb_madb' => ['madb', 'MADb Id'], 'utedb_premises_id' => ['premises', 'Premises Id'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(utedb_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_madb)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_premises_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_created)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_updated)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_id)%%>', safe_html($urow['utedb_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_id)%%>', html_attr($row['utedb_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_id)%%>', urlencode($urow['utedb_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_madb)%%>', safe_html($urow['utedb_madb']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_madb)%%>', html_attr($row['utedb_madb']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_madb)%%>', urlencode($urow['utedb_madb']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_premises_id)%%>', safe_html($urow['utedb_premises_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_premises_id)%%>', html_attr($row['utedb_premises_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_premises_id)%%>', urlencode($urow['utedb_premises_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_created)%%>', safe_html($urow['utedb_created']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_created)%%>', urlencode($urow['utedb_created']), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_updated)%%>', safe_html($urow['utedb_updated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_updated)%%>', urlencode($urow['utedb_updated']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(utedb_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_madb)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_madb)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_premises_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_premises_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_created)%%>', '<%%creationTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_created)%%>', urlencode('<%%creationTimestamp%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_updated)%%>', '<%%editingTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_updated)%%>', urlencode('<%%editingTimestamp%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tutedb_madb_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'utedb_autofill.php?rnd1=$rnd1&mfk=utedb_madb&id=' + encodeURIComponent('".addslashes($row['utedb_madb'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'utedb_autofill.php?rnd1=$rnd1&mfk=utedb_madb&id=' + encodeURIComponent(AppGini.current_utedb_madb{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#utedb_madb$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($allowInsert || $allowUpdate) ? "\$j('#utedb_madb$rnd1').prop('disabled', false); " : "\$j('#utedb_madb$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#utedb_madb_caption').length) \$j('#utedb_madb_caption').click(function() { utedb_madb_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('utedb');
	if($hasSelectedId) {
		$jdata = get_joined_record('utedb', $selectedId);
		if($jdata === false) $jdata = get_defaults('utedb');
		$rdata = $row;
	}
	$templateCode .= loadView('utedb-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: utedb_dv
	if(function_exists('utedb_dv')) {
		$args = [];
		utedb_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}