<?php

// Data functions (insert, update, delete, form) for table utedb

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function utedb_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('utedb');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'utedb_madb' => Request::lookup('utedb_madb', ''),
		'utedb_what1' => Request::lookup('utedb_madb'),
		'utedb_who1' => Request::lookup('utedb_madb'),
		'utedb_when1' => Request::lookup('utedb_madb'),
		'utedb_which1' => Request::lookup('utedb_madb'),
		'utedb_where1' => Request::lookup('utedb_madb'),
		'utedb_why1' => Request::lookup('utedb_madb'),
		'utedb_howr1' => Request::lookup('utedb_madb'),
		'utedb_hows1' => Request::lookup('utedb_madb'),
		'utedb_howq1' => Request::lookup('utedb_madb'),
		'utedb_howt1' => Request::lookup('utedb_madb'),
		'utedb_why2' => Request::lookup('utedb_madb'),
		'utedb_why3' => Request::lookup('utedb_madb'),
		'utedb_where2' => Request::lookup('utedb_madb'),
		'utedb_where3' => Request::lookup('utedb_madb'),
		'utedb_which2' => Request::lookup('utedb_madb'),
		'utedb_which3' => Request::lookup('utedb_madb'),
		'utedb_when2' => Request::lookup('utedb_madb'),
		'utedb_when3' => Request::lookup('utedb_madb'),
		'utedb_who2' => Request::lookup('utedb_madb'),
		'utedb_who3' => Request::lookup('utedb_madb'),
		'utedb_what2' => Request::lookup('utedb_madb'),
		'utedb_what3' => Request::lookup('utedb_madb'),
		'utedb_howr2' => Request::lookup('utedb_madb'),
		'utedb_howr3' => Request::lookup('utedb_madb'),
		'utedb_hows2' => Request::lookup('utedb_madb'),
		'utedb_hows3' => Request::lookup('utedb_madb'),
		'utedb_howq2' => Request::lookup('utedb_madb'),
		'utedb_howq3' => Request::lookup('utedb_madb'),
		'utedb_howt2' => Request::lookup('utedb_madb'),
		'utedb_howt3' => Request::lookup('utedb_madb'),
		'utedb_premises_id' => Request::lookup('utedb_madb'),
		'utedb_proof_image' => Request::fileUpload('utedb_proof_image', [
			'maxSize' => 512000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('utedb', 'utedb_proof_image', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('utedb', 'utedb_proof_image', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('utedb', 'utedb_proof_image', Request::val('SelectedID'));
			},
		]),
		'utedb_ai_audit' => Request::val('utedb_ai_audit', ''),
		'utedb_pc_audit' => Request::val('utedb_pc_audit', ''),
		'utedb_rda_audit' => Request::val('utedb_rda_audit', ''),
		'utedb_bb_audit' => Request::val('utedb_bb_audit', ''),
		'utedb_car' => Request::val('utedb_car', ''),
		'utedb_car_vid' => Request::fileUpload('utedb_car_vid', [
			'maxSize' => 512000,
			'types' => 'mov|avi|swf|asf|wmv|mpg|mpeg|mp4|flv',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('utedb', 'utedb_car_vid', Request::val('SelectedID'));
			},
		]),
		'utedb_col_tf' => Request::val('utedb_col_tf', ''),
		'utedb_delta_flag' => Request::val('utedb_delta_flag', ''),
		'utedb_created' => parseCode('<%%creationTimestamp%%>', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('utedb', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		utedb_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function utedb_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function utedb_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('utedb', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: utedb_before_delete
	if(function_exists('utedb_before_delete')) {
		$args = [];
		if(!utedb_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	// delete file stored in the 'utedb_proof_image' field
	$res = sql("SELECT `utedb_proof_image` FROM `utedb` WHERE `utedb_id`='{$selected_id}'", $eo);
	if($row = @db_fetch_row($res)) {
		if($row[0] != '') {
			@unlink(getUploadDir('') . $row[0]);
			$thumbDV = preg_replace('/\.(jpg|jpeg|gif|png|webp)$/i', '_dv.$1', $row[0]);
			$thumbTV = preg_replace('/\.(jpg|jpeg|gif|png|webp)$/i', '_tv.$1', $row[0]);
			@unlink(getUploadDir('') . $thumbTV);
			@unlink(getUploadDir('') . $thumbDV);
		}
	}

	// delete file stored in the 'utedb_car_vid' field
	$res = sql("SELECT `utedb_car_vid` FROM `utedb` WHERE `utedb_id`='{$selected_id}'", $eo);
	if($row = @db_fetch_row($res)) {
		if($row[0] != '') {
			@unlink(getUploadDir('') . $row[0]);
		}
	}

	sql("DELETE FROM `utedb` WHERE `utedb_id`='{$selected_id}'", $eo);

	// hook: utedb_after_delete
	if(function_exists('utedb_after_delete')) {
		$args = [];
		utedb_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='utedb' AND `pkValue`='{$selected_id}'", $eo);
}

function utedb_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('utedb', $selected_id, 'edit')) return false;

	$data = [
		'utedb_madb' => Request::lookup('utedb_madb', ''),
		'utedb_what1' => Request::lookup('utedb_madb'),
		'utedb_who1' => Request::lookup('utedb_madb'),
		'utedb_when1' => Request::lookup('utedb_madb'),
		'utedb_which1' => Request::lookup('utedb_madb'),
		'utedb_where1' => Request::lookup('utedb_madb'),
		'utedb_why1' => Request::lookup('utedb_madb'),
		'utedb_howr1' => Request::lookup('utedb_madb'),
		'utedb_hows1' => Request::lookup('utedb_madb'),
		'utedb_howq1' => Request::lookup('utedb_madb'),
		'utedb_howt1' => Request::lookup('utedb_madb'),
		'utedb_why2' => Request::lookup('utedb_madb'),
		'utedb_why3' => Request::lookup('utedb_madb'),
		'utedb_where2' => Request::lookup('utedb_madb'),
		'utedb_where3' => Request::lookup('utedb_madb'),
		'utedb_which2' => Request::lookup('utedb_madb'),
		'utedb_which3' => Request::lookup('utedb_madb'),
		'utedb_when2' => Request::lookup('utedb_madb'),
		'utedb_when3' => Request::lookup('utedb_madb'),
		'utedb_who2' => Request::lookup('utedb_madb'),
		'utedb_who3' => Request::lookup('utedb_madb'),
		'utedb_what2' => Request::lookup('utedb_madb'),
		'utedb_what3' => Request::lookup('utedb_madb'),
		'utedb_howr2' => Request::lookup('utedb_madb'),
		'utedb_howr3' => Request::lookup('utedb_madb'),
		'utedb_hows2' => Request::lookup('utedb_madb'),
		'utedb_hows3' => Request::lookup('utedb_madb'),
		'utedb_howq2' => Request::lookup('utedb_madb'),
		'utedb_howq3' => Request::lookup('utedb_madb'),
		'utedb_howt2' => Request::lookup('utedb_madb'),
		'utedb_howt3' => Request::lookup('utedb_madb'),
		'utedb_premises_id' => Request::lookup('utedb_madb'),
		'utedb_proof_image' => Request::fileUpload('utedb_proof_image', [
			'maxSize' => 512000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('utedb', 'utedb_proof_image', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('utedb', 'utedb_proof_image', 'dv'));
			},
			'removeOnSuccess' => true,
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// delete old file from server
				$oldFile = existing_value('utedb', 'utedb_proof_image', $selected_id);
				if(!$oldFile) return;

				@unlink(getUploadDir('') . $oldFile);

				// delete thumbnails
				preg_match('/^[a-z0-9_]+\.(jpg|jpeg|gif|png|webp)$/i', $oldFile, $m);
				$thumbDV = str_replace(".{$m[1]}ffffgggg", "_dv.{$m[1]}", $oldFile . 'ffffgggg');
				$thumbTV = str_replace(".{$m[1]}ffffgggg", "_tv.{$m[1]}", $oldFile . 'ffffgggg');
				@unlink(getUploadDir('') . $thumbTV);
				@unlink(getUploadDir('') . $thumbDV);
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('utedb', 'utedb_proof_image', $selected_id);
			},
		]),
		'utedb_ai_audit' => Request::val('utedb_ai_audit', ''),
		'utedb_pc_audit' => Request::val('utedb_pc_audit', ''),
		'utedb_rda_audit' => Request::val('utedb_rda_audit', ''),
		'utedb_bb_audit' => Request::val('utedb_bb_audit', ''),
		'utedb_car' => Request::val('utedb_car', ''),
		'utedb_car_vid' => Request::fileUpload('utedb_car_vid', [
			'maxSize' => 512000,
			'types' => 'mov|avi|swf|asf|wmv|mpg|mpeg|mp4|flv',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnSuccess' => true,
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// delete old file from server
				$oldFile = existing_value('utedb', 'utedb_car_vid', $selected_id);
				if(!$oldFile) return;

				@unlink(getUploadDir('') . $oldFile);
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('utedb', 'utedb_car_vid', $selected_id);
			},
		]),
		'utedb_col_tf' => Request::val('utedb_col_tf', ''),
		'utedb_delta_flag' => Request::val('utedb_delta_flag', ''),
		'utedb_updated' => parseCode('<%%editingTimestamp%%>', false, true),
	];

	if($data['utedb_madb'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'MADb Id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('utedb', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: utedb_before_update
	if(function_exists('utedb_before_update')) {
		$args = ['old_data' => $old_data];
		if(!utedb_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'utedb',
		backtick_keys_once($set),
		['`utedb_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="utedb_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('utedb', $data['selectedID'], calculated_fields()['utedb']);

	// hook: utedb_after_update
	if(function_exists('utedb_after_update')) {
		if($row = getRecord('utedb', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['utedb_id'];
		$args = ['old_data' => $old_data];
		if(!utedb_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('utedb', $selected_id);
}

function utedb_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('utedb');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('utedb', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('utedb', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('utedb', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_utedb_madb = Request::val('filterer_utedb_madb');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: utedb_madb
	$combo_utedb_madb = new DataCombo;
	// combobox: utedb_pc_audit
	$combo_utedb_pc_audit = new Combo;
	$combo_utedb_pc_audit->ListType = 0;
	$combo_utedb_pc_audit->MultipleSeparator = ', ';
	$combo_utedb_pc_audit->ListBoxHeight = 10;
	$combo_utedb_pc_audit->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/utedb.utedb_pc_audit.csv')) {
		$utedb_pc_audit_data = addslashes(implode('', @file(__DIR__ . '/hooks/utedb.utedb_pc_audit.csv')));
		$combo_utedb_pc_audit->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($utedb_pc_audit_data))));
		$combo_utedb_pc_audit->ListData = $combo_utedb_pc_audit->ListItem;
	} else {
		$combo_utedb_pc_audit->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("True;;False"))));
		$combo_utedb_pc_audit->ListData = $combo_utedb_pc_audit->ListItem;
	}
	$combo_utedb_pc_audit->SelectName = 'utedb_pc_audit';
	// combobox: utedb_rda_audit
	$combo_utedb_rda_audit = new Combo;
	$combo_utedb_rda_audit->ListType = 0;
	$combo_utedb_rda_audit->MultipleSeparator = ', ';
	$combo_utedb_rda_audit->ListBoxHeight = 10;
	$combo_utedb_rda_audit->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/utedb.utedb_rda_audit.csv')) {
		$utedb_rda_audit_data = addslashes(implode('', @file(__DIR__ . '/hooks/utedb.utedb_rda_audit.csv')));
		$combo_utedb_rda_audit->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($utedb_rda_audit_data))));
		$combo_utedb_rda_audit->ListData = $combo_utedb_rda_audit->ListItem;
	} else {
		$combo_utedb_rda_audit->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("True;;False"))));
		$combo_utedb_rda_audit->ListData = $combo_utedb_rda_audit->ListItem;
	}
	$combo_utedb_rda_audit->SelectName = 'utedb_rda_audit';
	// combobox: utedb_bb_audit
	$combo_utedb_bb_audit = new Combo;
	$combo_utedb_bb_audit->ListType = 0;
	$combo_utedb_bb_audit->MultipleSeparator = ', ';
	$combo_utedb_bb_audit->ListBoxHeight = 10;
	$combo_utedb_bb_audit->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/utedb.utedb_bb_audit.csv')) {
		$utedb_bb_audit_data = addslashes(implode('', @file(__DIR__ . '/hooks/utedb.utedb_bb_audit.csv')));
		$combo_utedb_bb_audit->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($utedb_bb_audit_data))));
		$combo_utedb_bb_audit->ListData = $combo_utedb_bb_audit->ListItem;
	} else {
		$combo_utedb_bb_audit->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("True;;False"))));
		$combo_utedb_bb_audit->ListData = $combo_utedb_bb_audit->ListItem;
	}
	$combo_utedb_bb_audit->SelectName = 'utedb_bb_audit';
	// combobox: utedb_car
	$combo_utedb_car = new Combo;
	$combo_utedb_car->ListType = 0;
	$combo_utedb_car->MultipleSeparator = ', ';
	$combo_utedb_car->ListBoxHeight = 10;
	$combo_utedb_car->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/utedb.utedb_car.csv')) {
		$utedb_car_data = addslashes(implode('', @file(__DIR__ . '/hooks/utedb.utedb_car.csv')));
		$combo_utedb_car->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($utedb_car_data))));
		$combo_utedb_car->ListData = $combo_utedb_car->ListItem;
	} else {
		$combo_utedb_car->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("1;;2;;3;;4;;5"))));
		$combo_utedb_car->ListData = $combo_utedb_car->ListItem;
	}
	$combo_utedb_car->SelectName = 'utedb_car';
	// combobox: utedb_delta_flag
	$combo_utedb_delta_flag = new Combo;
	$combo_utedb_delta_flag->ListType = 0;
	$combo_utedb_delta_flag->MultipleSeparator = ', ';
	$combo_utedb_delta_flag->ListBoxHeight = 10;
	$combo_utedb_delta_flag->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/utedb.utedb_delta_flag.csv')) {
		$utedb_delta_flag_data = addslashes(implode('', @file(__DIR__ . '/hooks/utedb.utedb_delta_flag.csv')));
		$combo_utedb_delta_flag->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($utedb_delta_flag_data))));
		$combo_utedb_delta_flag->ListData = $combo_utedb_delta_flag->ListItem;
	} else {
		$combo_utedb_delta_flag->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Red;;Green"))));
		$combo_utedb_delta_flag->ListData = $combo_utedb_delta_flag->ListItem;
	}
	$combo_utedb_delta_flag->SelectName = 'utedb_delta_flag';

	if($hasSelectedId) {
		if(!($row = getRecord('utedb', $selectedId))) {
			return error_message($Translation['No records found'], 'utedb_view.php', false);
		}
		$combo_utedb_madb->SelectedData = $row['utedb_madb'];
		$combo_utedb_pc_audit->SelectedData = $row['utedb_pc_audit'];
		$combo_utedb_rda_audit->SelectedData = $row['utedb_rda_audit'];
		$combo_utedb_bb_audit->SelectedData = $row['utedb_bb_audit'];
		$combo_utedb_car->SelectedData = $row['utedb_car'];
		$combo_utedb_delta_flag->SelectedData = $row['utedb_delta_flag'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_utedb_madb->SelectedData = $filterer_utedb_madb;
		$combo_utedb_pc_audit->SelectedText = (isset($filterField[1]) && $filterField[1] == '36' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_utedb_rda_audit->SelectedText = (isset($filterField[1]) && $filterField[1] == '37' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_utedb_bb_audit->SelectedText = (isset($filterField[1]) && $filterField[1] == '38' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_utedb_car->SelectedText = (isset($filterField[1]) && $filterField[1] == '39' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_utedb_delta_flag->SelectedText = (isset($filterField[1]) && $filterField[1] == '42' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_utedb_madb->HTML = '<span id="utedb_madb-container' . $rnd1 . '"></span><input type="hidden" name="utedb_madb" id="utedb_madb' . $rnd1 . '" value="' . html_attr($combo_utedb_madb->SelectedData) . '">';
	$combo_utedb_madb->MatchText = '<span id="utedb_madb-container-readonly' . $rnd1 . '"></span><input type="hidden" name="utedb_madb" id="utedb_madb' . $rnd1 . '" value="' . html_attr($combo_utedb_madb->SelectedData) . '">';
	$combo_utedb_pc_audit->Render();
	$combo_utedb_rda_audit->Render();
	$combo_utedb_bb_audit->Render();
	$combo_utedb_car->Render();
	$combo_utedb_delta_flag->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_utedb_madb__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['utedb_madb'] : htmlspecialchars($filterer_utedb_madb, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(utedb_madb_reload__RAND__) == 'function') utedb_madb_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function utedb_madb_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#utedb_madb-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_utedb_madb__RAND__.value, t: 'utedb', f: 'utedb_madb' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="utedb_madb"]').val(resp.results[0].id);
							$j('[id=utedb_madb-container-readonly__RAND__]').html('<span class="match-text" id="utedb_madb-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=madb_view_parent]').hide(); } else { $j('.btn[id=madb_view_parent]').show(); }


							if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'utedb', f: 'utedb_madb' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_utedb_madb__RAND__.value = e.added.id;
				AppGini.current_utedb_madb__RAND__.text = e.added.text;
				$j('[name="utedb_madb"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=madb_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
			});

			if(!$j("#utedb_madb-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_utedb_madb__RAND__.value, t: 'utedb', f: 'utedb_madb' },
					success: function(resp) {
						$j('[name="utedb_madb"]').val(resp.results[0].id);
						$j('[id=utedb_madb-container-readonly__RAND__]').html('<span class="match-text" id="utedb_madb-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=madb_view_parent]').hide(); } else { $j('.btn[id=madb_view_parent]').show(); }

						if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_utedb_madb__RAND__.value, t: 'utedb', f: 'utedb_madb' },
				success: function(resp) {
					$j('[id=utedb_madb-container__RAND__], [id=utedb_madb-container-readonly__RAND__]').html('<span class="match-text" id="utedb_madb-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=madb_view_parent]').hide(); } else { $j('.btn[id=madb_view_parent]').show(); }

					if(typeof(utedb_madb_update_autofills__RAND__) == 'function') utedb_madb_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/utedb_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/utedb_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Universal TEDb details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#utedb_madb').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#utedb_madb_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#utedb_proof_image').replaceWith('<div class=\"form-control-static\" id=\"utedb_proof_image\">' + (\$j('#utedb_proof_image').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#utedb_ai_audit').replaceWith('<div class=\"form-control-static\" id=\"utedb_ai_audit\">' + (\$j('#utedb_ai_audit').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#utedb_pc_audit').replaceWith('<div class=\"form-control-static\" id=\"utedb_pc_audit\">' + (\$j('#utedb_pc_audit').val() || '') + '</div>'); \$j('#utedb_pc_audit-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#utedb_rda_audit').replaceWith('<div class=\"form-control-static\" id=\"utedb_rda_audit\">' + (\$j('#utedb_rda_audit').val() || '') + '</div>'); \$j('#utedb_rda_audit-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#utedb_bb_audit').replaceWith('<div class=\"form-control-static\" id=\"utedb_bb_audit\">' + (\$j('#utedb_bb_audit').val() || '') + '</div>'); \$j('#utedb_bb_audit-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#utedb_car').replaceWith('<div class=\"form-control-static\" id=\"utedb_car\">' + (\$j('#utedb_car').val() || '') + '</div>'); \$j('#utedb_car-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#utedb_car_vid').parent().replaceWith(`<div class=\"form-control-static\" id=\"utedb_car_vid\">\${\$j('#utedb_car_vid').val() || ''}\${\$j('#utedb_car_vid').val() ? '<a target=\"_blank\" class=\"hspacer-lg\" href=\"' + \$j('#utedb_car_vid').val() + '\" target=\"_blank\"><i class=\"glyphicon glyphicon-globe\"></i></a>' : ''}</div>`);\n";
		$jsReadOnly .= "\t\$j('#utedb_col_tf').replaceWith('<div class=\"form-control-static\" id=\"utedb_col_tf\">' + (\$j('#utedb_col_tf').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#utedb_delta_flag').replaceWith('<div class=\"form-control-static\" id=\"utedb_delta_flag\">' + (\$j('#utedb_delta_flag').val() || '') + '</div>'); \$j('#utedb_delta_flag-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(utedb_madb)%%>', $combo_utedb_madb->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_madb)%%>', $combo_utedb_madb->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(utedb_madb)%%>', urlencode($combo_utedb_madb->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(utedb_pc_audit)%%>', $combo_utedb_pc_audit->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_pc_audit)%%>', $combo_utedb_pc_audit->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(utedb_rda_audit)%%>', $combo_utedb_rda_audit->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_rda_audit)%%>', $combo_utedb_rda_audit->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(utedb_bb_audit)%%>', $combo_utedb_bb_audit->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_bb_audit)%%>', $combo_utedb_bb_audit->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(utedb_car)%%>', $combo_utedb_car->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_car)%%>', $combo_utedb_car->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(utedb_delta_flag)%%>', $combo_utedb_delta_flag->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(utedb_delta_flag)%%>', $combo_utedb_delta_flag->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['utedb_madb' => ['madb', 'MADb Id'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(utedb_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_madb)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_proof_image)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="utedb_proof_image" id="utedb_proof_image" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="512000" style="max-width: calc(100% - 1.5rem);" accept="capture=camera,image/*">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($allowUpdate && $row['utedb_proof_image'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(utedb_proof_image)%%>', '<input type="checkbox" name="utedb_proof_image_remove" id="utedb_proof_image_remove" value="1"> <label for="utedb_proof_image_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(utedb_proof_image)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(utedb_ai_audit)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_pc_audit)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_rda_audit)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_bb_audit)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_car)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_car_vid)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="utedb_car_vid" id="utedb_car_vid" data-filetypes="mov|avi|swf|asf|wmv|mpg|mpeg|mp4|flv" data-maxsize="512000" style="max-width: calc(100% - 1.5rem);" accept=".mov,.avi,.swf,.asf,.wmv,.mpg,.mpeg,.mp4,.flv">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($allowUpdate && $row['utedb_car_vid'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(utedb_car_vid)%%>', '<input type="checkbox" name="utedb_car_vid_remove" id="utedb_car_vid_remove" value="1"> <label for="utedb_car_vid_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(utedb_car_vid)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(utedb_col_tf)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_delta_flag)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_created)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(utedb_updated)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_id)%%>', safe_html($urow['utedb_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_id)%%>', html_attr($row['utedb_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_id)%%>', urlencode($urow['utedb_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_madb)%%>', safe_html($urow['utedb_madb']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_madb)%%>', html_attr($row['utedb_madb']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_madb)%%>', urlencode($urow['utedb_madb']), $templateCode);
		$row['utedb_proof_image'] = ($row['utedb_proof_image'] != '' ? $row['utedb_proof_image'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_proof_image)%%>', safe_html($urow['utedb_proof_image']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_proof_image)%%>', html_attr($row['utedb_proof_image']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_proof_image)%%>', urlencode($urow['utedb_proof_image']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_ai_audit)%%>', safe_html($urow['utedb_ai_audit']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_ai_audit)%%>', html_attr($row['utedb_ai_audit']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_ai_audit)%%>', urlencode($urow['utedb_ai_audit']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_pc_audit)%%>', safe_html($urow['utedb_pc_audit']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_pc_audit)%%>', html_attr($row['utedb_pc_audit']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_pc_audit)%%>', urlencode($urow['utedb_pc_audit']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_rda_audit)%%>', safe_html($urow['utedb_rda_audit']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_rda_audit)%%>', html_attr($row['utedb_rda_audit']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_rda_audit)%%>', urlencode($urow['utedb_rda_audit']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_bb_audit)%%>', safe_html($urow['utedb_bb_audit']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_bb_audit)%%>', html_attr($row['utedb_bb_audit']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_bb_audit)%%>', urlencode($urow['utedb_bb_audit']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_car)%%>', safe_html($urow['utedb_car']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_car)%%>', html_attr($row['utedb_car']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_car)%%>', urlencode($urow['utedb_car']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_car_vid)%%>', safe_html($urow['utedb_car_vid']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_car_vid)%%>', html_attr($row['utedb_car_vid']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_car_vid)%%>', urlencode($urow['utedb_car_vid']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_col_tf)%%>', safe_html($urow['utedb_col_tf']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_col_tf)%%>', html_attr($row['utedb_col_tf']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_col_tf)%%>', urlencode($urow['utedb_col_tf']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(utedb_delta_flag)%%>', safe_html($urow['utedb_delta_flag']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(utedb_delta_flag)%%>', html_attr($row['utedb_delta_flag']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_delta_flag)%%>', urlencode($urow['utedb_delta_flag']), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_created)%%>', safe_html($urow['utedb_created']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_created)%%>', urlencode($urow['utedb_created']), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_updated)%%>', safe_html($urow['utedb_updated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_updated)%%>', urlencode($urow['utedb_updated']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(utedb_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_madb)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_madb)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_proof_image)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_ai_audit)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_ai_audit)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_pc_audit)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_pc_audit)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_rda_audit)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_rda_audit)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_bb_audit)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_bb_audit)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_car)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_car)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_car_vid)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_car_vid)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_col_tf)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_col_tf)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_delta_flag)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_delta_flag)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_created)%%>', '<%%creationTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_created)%%>', urlencode('<%%creationTimestamp%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(utedb_updated)%%>', '<%%editingTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(utedb_updated)%%>', urlencode('<%%editingTimestamp%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
			$templateCode.="\n\tif(document.getElementById('utedb_car_vidEdit')) { document.getElementById('utedb_car_vidEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('utedb_car_vidEditLink')) { document.getElementById('utedb_car_vidEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tutedb_madb_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'utedb_autofill.php?rnd1=$rnd1&mfk=utedb_madb&id=' + encodeURIComponent('".addslashes($row['utedb_madb'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'utedb_autofill.php?rnd1=$rnd1&mfk=utedb_madb&id=' + encodeURIComponent(AppGini.current_utedb_madb{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#utedb_madb$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($allowInsert || $allowUpdate) ? "\$j('#utedb_madb$rnd1').prop('disabled', false); " : "\$j('#utedb_madb$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#utedb_madb_caption').length) \$j('#utedb_madb_caption').click(function() { utedb_madb_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('utedb');
	if($hasSelectedId) {
		$jdata = get_joined_record('utedb', $selectedId);
		if($jdata === false) $jdata = get_defaults('utedb');
		$rdata = $row;
	}
	$templateCode .= loadView('utedb-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: utedb_dv
	if(function_exists('utedb_dv')) {
		$args = [];
		utedb_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}