<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/whats.php');
	include_once(__DIR__ . '/whats_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('whats');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'whats';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`whats`.`whats_id`" => "whats_id",
		"`whats`.`whats_what1`" => "whats_what1",
		"`whats`.`whats_what2`" => "whats_what2",
		"`whats`.`whats_what3`" => "whats_what3",
		"`whats`.`whats_description`" => "whats_description",
		"`whats`.`whats_created`" => "whats_created",
		"`whats`.`whats_updated`" => "whats_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`whats`.`whats_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`whats`.`whats_created`',
		7 => '`whats`.`whats_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`whats`.`whats_id`" => "whats_id",
		"`whats`.`whats_what1`" => "whats_what1",
		"`whats`.`whats_what2`" => "whats_what2",
		"`whats`.`whats_what3`" => "whats_what3",
		"`whats`.`whats_description`" => "whats_description",
		"`whats`.`whats_created`" => "whats_created",
		"`whats`.`whats_updated`" => "whats_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`whats`.`whats_id`" => "Whats id",
		"`whats`.`whats_what1`" => "What1 (Task English)",
		"`whats`.`whats_what2`" => "What2 (Task Hindi)",
		"`whats`.`whats_what3`" => "What3 (If Any)",
		"`whats`.`whats_description`" => "Description",
		"`whats`.`whats_created`" => "Created AT",
		"`whats`.`whats_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`whats`.`whats_id`" => "whats_id",
		"`whats`.`whats_what1`" => "whats_what1",
		"`whats`.`whats_what2`" => "whats_what2",
		"`whats`.`whats_what3`" => "whats_what3",
		"`whats`.`whats_description`" => "whats_description",
		"`whats`.`whats_created`" => "whats_created",
		"`whats`.`whats_updated`" => "whats_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`whats` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'whats_view.php';
	$x->TableTitle = 'Whats';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`whats`.`whats_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Whats id', 'What1 (Task English)', 'What2 (Task Hindi)', 'What3 (If Any)', 'Description', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['whats_id', 'whats_what1', 'whats_what2', 'whats_what3', 'whats_description', 'whats_created', 'whats_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/whats_templateTV.html';
	$x->SelectedTemplate = 'templates/whats_templateTVS.html';
	$x->TemplateDV = 'templates/whats_templateDV.html';
	$x->TemplateDVP = 'templates/whats_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: whats_init
	$render = true;
	if(function_exists('whats_init')) {
		$args = [];
		$render = whats_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: whats_header
	$headerCode = '';
	if(function_exists('whats_header')) {
		$args = [];
		$headerCode = whats_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: whats_footer
	$footerCode = '';
	if(function_exists('whats_footer')) {
		$args = [];
		$footerCode = whats_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
