<?php

// Data functions (insert, update, delete, form) for table whens

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function whens_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('whens');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'whens_when1' => Request::val('whens_when1', ''),
		'whens_when2' => Request::val('whens_when2', ''),
		'whens_when3' => time24(Request::val('whens_when3', '')),
		'whens_description' => br2nl(Request::val('whens_description', '')),
		'whens_created' => parseCode('<%%creationTimestamp%%>', true, true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('whens', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		whens_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function whens_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function whens_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('whens', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: whens_before_delete
	if(function_exists('whens_before_delete')) {
		$args = [];
		if(!whens_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	// child table: madb
	$res = sql("SELECT `whens_id` FROM `whens` WHERE `whens_id`='{$selected_id}'", $eo);
	$whens_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `madb` WHERE `madb_when1`='" . makeSafe($whens_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="madb_view.php?filterer_madb_when1=' . urlencode($whens_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'madb'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'madb'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `whens_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `whens_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: premises
	$res = sql("SELECT `whens_id` FROM `whens` WHERE `whens_id`='{$selected_id}'", $eo);
	$whens_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `premises` WHERE `premjees_opening`='" . makeSafe($whens_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="premises_view.php?filterer_premjees_opening=' . urlencode($whens_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'premises'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'premises'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `whens_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `whens_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: premises
	$res = sql("SELECT `whens_id` FROM `whens` WHERE `whens_id`='{$selected_id}'", $eo);
	$whens_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `premises` WHERE `premjees_closing`='" . makeSafe($whens_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="premises_view.php?filterer_premjees_closing=' . urlencode($whens_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'premises'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'premises'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `whens_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `whens_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `whens` WHERE `whens_id`='{$selected_id}'", $eo);

	// hook: whens_after_delete
	if(function_exists('whens_after_delete')) {
		$args = [];
		whens_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='whens' AND `pkValue`='{$selected_id}'", $eo);
}

function whens_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('whens', $selected_id, 'edit')) return false;

	$data = [
		'whens_when1' => Request::val('whens_when1', ''),
		'whens_when2' => Request::val('whens_when2', ''),
		'whens_when3' => time24(Request::val('whens_when3', '')),
		'whens_description' => br2nl(Request::val('whens_description', '')),
		'whens_updated' => parseCode('<%%editingTimestamp%%>', false, true),
	];

	if($data['whens_when1'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'When1 (Frequency)': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['whens_when2'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'When2 (Sessions)': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['whens_when3'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'When3 (Specific Time)': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('whens', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: whens_before_update
	if(function_exists('whens_before_update')) {
		$args = ['old_data' => $old_data];
		if(!whens_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'whens',
		backtick_keys_once($set),
		['`whens_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="whens_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('whens', $data['selectedID'], calculated_fields()['whens']);

	// hook: whens_after_update
	if(function_exists('whens_after_update')) {
		if($row = getRecord('whens', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['whens_id'];
		$args = ['old_data' => $old_data];
		if(!whens_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('whens', $selected_id);
}

function whens_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('whens');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('whens', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('whens', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('whens', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: whens_when1
	$combo_whens_when1 = new Combo;
	$combo_whens_when1->ListType = 0;
	$combo_whens_when1->MultipleSeparator = ', ';
	$combo_whens_when1->ListBoxHeight = 10;
	$combo_whens_when1->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/whens.whens_when1.csv')) {
		$whens_when1_data = addslashes(implode('', @file(__DIR__ . '/hooks/whens.whens_when1.csv')));
		$combo_whens_when1->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($whens_when1_data))));
		$combo_whens_when1->ListData = $combo_whens_when1->ListItem;
	} else {
		$combo_whens_when1->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Daily;;Weekly;;Bi-Weekly;;Monthly;;Bi-Monthly;;Yearly"))));
		$combo_whens_when1->ListData = $combo_whens_when1->ListItem;
	}
	$combo_whens_when1->SelectName = 'whens_when1';
	$combo_whens_when1->AllowNull = false;
	// combobox: whens_when2
	$combo_whens_when2 = new Combo;
	$combo_whens_when2->ListType = 0;
	$combo_whens_when2->MultipleSeparator = ', ';
	$combo_whens_when2->ListBoxHeight = 10;
	$combo_whens_when2->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/whens.whens_when2.csv')) {
		$whens_when2_data = addslashes(implode('', @file(__DIR__ . '/hooks/whens.whens_when2.csv')));
		$combo_whens_when2->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($whens_when2_data))));
		$combo_whens_when2->ListData = $combo_whens_when2->ListItem;
	} else {
		$combo_whens_when2->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Opening;;Closing;;Morning;;Evening;;DayTime"))));
		$combo_whens_when2->ListData = $combo_whens_when2->ListItem;
	}
	$combo_whens_when2->SelectName = 'whens_when2';
	$combo_whens_when2->AllowNull = false;
	// combobox: whens_when3
	$combo_whens_when3 = new Combo;
	$combo_whens_when3->ListType = 0;
	$combo_whens_when3->MultipleSeparator = ', ';
	$combo_whens_when3->ListBoxHeight = 10;
	$combo_whens_when3->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/whens.whens_when3.csv')) {
		$whens_when3_data = addslashes(implode('', @file(__DIR__ . '/hooks/whens.whens_when3.csv')));
		$combo_whens_when3->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($whens_when3_data))));
		$combo_whens_when3->ListData = $combo_whens_when3->ListItem;
	} else {
		$combo_whens_when3->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("06:55;;07:00;;07:05;;07:10;;07:15;;07:20;;07:25;;07:30;;07:35;;07:40;;07:45;;07:50;;07:55;;08:00;;08:05;;08:10;;08:15;;08:20;;08:25;;08:30;;08:35;;08:40;;08:45;;08:50;;08:55;;09:00;;09:05;;09:10;;09:15;;09:20;;09:25;;09:30;;09:35;;09:40;;09:45;;09:50;;09:55;;10:00;;10:05;;10:10;;10:15;;10:20;;10:25;;10:30;;10:35;;10:40;;10:45;;10:50;;10:55;;11:00;;11:05;;11:10;;11:15;;11:20;;11:25;;11:30;;11:35;;11:40;;11:45;;11:50;;11:55;;12:00;;12:05;;12:10;;12:15;;12:20;;12:25;;12:30;;12:35;;12:40;;12:45;;12:50;;12:55;;13:00;;13:05;;13:10;;13:15;;13:20;;13:25;;13:30;;13:35;;13:40;;13:45;;13:50;;13:55;;14:00;;14:05;;14:10;;14:15;;14:20;;14:25;;14:30;;14:35;;14:40;;14:45;;14:50;;14:55;;15:00;;15:05;;15:10;;15:15;;15:20;;15:25;;15:30;;15:35;;15:40;;15:45;;15:50;;15:55;;16:00;;16:05;;16:10;;16:15;;16:20;;16:25;;16:30;;16:35;;16:40;;16:45;;16:50;;16:55;;17:00;;17:05;;17:10;;17:15;;17:20;;17:25;;17:30;;17:35;;17:40;;17:45;;17:50;;17:55;;18:00;;18:05;;18:10;;18:15;;18:20;;18:25;;18:30;;18:35;;18:40;;18:45;;18:50;;18:55;;19:00;;19:05;;19:10;;19:15;;19:20;;19:25;;19:30;;19:35;;19:40;;19:45;;19:50;;19:55;;20:00;;20:05;;20:10;;20:15;;20:20;;20:25;;20:30;;20:35;;20:40;;20:45;;20:50;;20:55;;21:00;;21:05;;21:10;;21:15"))));
		$combo_whens_when3->ListData = $combo_whens_when3->ListItem;
	}
	$combo_whens_when3->SelectName = 'whens_when3';
	$combo_whens_when3->AllowNull = false;

	if($hasSelectedId) {
		if(!($row = getRecord('whens', $selectedId))) {
			return error_message($Translation['No records found'], 'whens_view.php', false);
		}
		$combo_whens_when1->SelectedData = $row['whens_when1'];
		$combo_whens_when2->SelectedData = $row['whens_when2'];
		$combo_whens_when3->SelectedData = $row['whens_when3'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_whens_when1->SelectedText = (isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_whens_when2->SelectedText = (isset($filterField[1]) && $filterField[1] == '3' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_whens_when3->SelectedText = (isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_whens_when1->Render();
	$combo_whens_when2->Render();
	$combo_whens_when3->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		$j(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/whens_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/whens_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'When details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#whens_when1').replaceWith('<div class=\"form-control-static\" id=\"whens_when1\">' + (\$j('#whens_when1').val() || '') + '</div>'); \$j('#whens_when1-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#whens_when2').replaceWith('<div class=\"form-control-static\" id=\"whens_when2\">' + (\$j('#whens_when2').val() || '') + '</div>'); \$j('#whens_when2-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#whens_when3').replaceWith('<div class=\"form-control-static\" id=\"whens_when3\">' + (\$j('#whens_when3').val() || '') + '</div>'); \$j('#whens_when3-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#whens_description').replaceWith('<div class=\"form-control-static\" id=\"whens_description\">' + (\$j('#whens_description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('#whens_when3').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: true, showInputs: false, disableFocus: true, minuteStep: AppGini.config.timeFieldMinutesStep || 5 });";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(whens_when1)%%>', $combo_whens_when1->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(whens_when1)%%>', $combo_whens_when1->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(whens_when2)%%>', $combo_whens_when2->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(whens_when2)%%>', $combo_whens_when2->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(whens_when3)%%>', $combo_whens_when3->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(whens_when3)%%>', $combo_whens_when3->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(whens_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whens_when1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whens_when2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whens_when3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whens_description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whens_created)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(whens_updated)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(whens_id)%%>', safe_html($urow['whens_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(whens_id)%%>', html_attr($row['whens_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_id)%%>', urlencode($urow['whens_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(whens_when1)%%>', safe_html($urow['whens_when1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(whens_when1)%%>', html_attr($row['whens_when1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_when1)%%>', urlencode($urow['whens_when1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(whens_when2)%%>', safe_html($urow['whens_when2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(whens_when2)%%>', html_attr($row['whens_when2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_when2)%%>', urlencode($urow['whens_when2']), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_when3)%%>', time12(html_attr($row['whens_when3'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_when3)%%>', urlencode(time12($urow['whens_when3'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_description)%%>', safe_html($urow['whens_description'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_description)%%>', urlencode($urow['whens_description']), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_created)%%>', safe_html($urow['whens_created']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_created)%%>', urlencode($urow['whens_created']), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_updated)%%>', safe_html($urow['whens_updated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_updated)%%>', urlencode($urow['whens_updated']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(whens_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_when1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_when1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_when2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_when2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_when3)%%>', time12(''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_when3)%%>', urlencode(time12('')), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_created)%%>', '<%%creationTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_created)%%>', urlencode('<%%creationTimestamp%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(whens_updated)%%>', '<%%editingTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(whens_updated)%%>', urlencode('<%%editingTimestamp%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('whens');
	if($hasSelectedId) {
		$jdata = get_joined_record('whens', $selectedId);
		if($jdata === false) $jdata = get_defaults('whens');
		$rdata = $row;
	}
	$templateCode .= loadView('whens-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: whens_dv
	if(function_exists('whens_dv')) {
		$args = [];
		whens_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}