<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/wheres.php');
	include_once(__DIR__ . '/wheres_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('wheres');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'wheres';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`wheres`.`wheres_id`" => "wheres_id",
		"`wheres`.`wheres_where1`" => "wheres_where1",
		"`wheres`.`wheres_where2`" => "wheres_where2",
		"`wheres`.`wheres_where3`" => "wheres_where3",
		"`wheres`.`wheres_description`" => "wheres_description",
		"`wheres`.`wheres_created`" => "wheres_created",
		"`wheres`.`wheres_updated`" => "wheres_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`wheres`.`wheres_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`wheres`.`wheres_created`',
		7 => '`wheres`.`wheres_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`wheres`.`wheres_id`" => "wheres_id",
		"`wheres`.`wheres_where1`" => "wheres_where1",
		"`wheres`.`wheres_where2`" => "wheres_where2",
		"`wheres`.`wheres_where3`" => "wheres_where3",
		"`wheres`.`wheres_description`" => "wheres_description",
		"`wheres`.`wheres_created`" => "wheres_created",
		"`wheres`.`wheres_updated`" => "wheres_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`wheres`.`wheres_id`" => "Wheres id",
		"`wheres`.`wheres_where1`" => "Where1 (Main Place)",
		"`wheres`.`wheres_where2`" => "Wheres2 (Sub Place)",
		"`wheres`.`wheres_where3`" => "Where3 (If Any)",
		"`wheres`.`wheres_description`" => "Description",
		"`wheres`.`wheres_created`" => "Created AT",
		"`wheres`.`wheres_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`wheres`.`wheres_id`" => "wheres_id",
		"`wheres`.`wheres_where1`" => "wheres_where1",
		"`wheres`.`wheres_where2`" => "wheres_where2",
		"`wheres`.`wheres_where3`" => "wheres_where3",
		"`wheres`.`wheres_description`" => "wheres_description",
		"`wheres`.`wheres_created`" => "wheres_created",
		"`wheres`.`wheres_updated`" => "wheres_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`wheres` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'wheres_view.php';
	$x->TableTitle = 'Wheres';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`wheres`.`wheres_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Wheres id', 'Where1 (Main Place)', 'Wheres2 (Sub Place)', 'Where3 (If Any)', 'Description', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['wheres_id', 'wheres_where1', 'wheres_where2', 'wheres_where3', 'wheres_description', 'wheres_created', 'wheres_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/wheres_templateTV.html';
	$x->SelectedTemplate = 'templates/wheres_templateTVS.html';
	$x->TemplateDV = 'templates/wheres_templateDV.html';
	$x->TemplateDVP = 'templates/wheres_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: wheres_init
	$render = true;
	if(function_exists('wheres_init')) {
		$args = [];
		$render = wheres_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: wheres_header
	$headerCode = '';
	if(function_exists('wheres_header')) {
		$args = [];
		$headerCode = wheres_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: wheres_footer
	$footerCode = '';
	if(function_exists('wheres_footer')) {
		$args = [];
		$footerCode = wheres_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
