<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/whichs.php');
	include_once(__DIR__ . '/whichs_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('whichs');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'whichs';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`whichs`.`whichs_id`" => "whichs_id",
		"`whichs`.`whichs_which1`" => "whichs_which1",
		"`whichs`.`whichs_which2`" => "whichs_which2",
		"`whichs`.`whichs_which3`" => "whichs_which3",
		"`whichs`.`whichs_description`" => "whichs_description",
		"`whichs`.`whichs_created`" => "whichs_created",
		"`whichs`.`whichs_updated`" => "whichs_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`whichs`.`whichs_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`whichs`.`whichs_created`',
		7 => '`whichs`.`whichs_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`whichs`.`whichs_id`" => "whichs_id",
		"`whichs`.`whichs_which1`" => "whichs_which1",
		"`whichs`.`whichs_which2`" => "whichs_which2",
		"`whichs`.`whichs_which3`" => "whichs_which3",
		"`whichs`.`whichs_description`" => "whichs_description",
		"`whichs`.`whichs_created`" => "whichs_created",
		"`whichs`.`whichs_updated`" => "whichs_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`whichs`.`whichs_id`" => "Whichs id",
		"`whichs`.`whichs_which1`" => "Which1 (Main Thing)",
		"`whichs`.`whichs_which2`" => "Which2 (Sub Thing)",
		"`whichs`.`whichs_which3`" => "Which3 (If Any)",
		"`whichs`.`whichs_description`" => "Description",
		"`whichs`.`whichs_created`" => "Created AT",
		"`whichs`.`whichs_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`whichs`.`whichs_id`" => "whichs_id",
		"`whichs`.`whichs_which1`" => "whichs_which1",
		"`whichs`.`whichs_which2`" => "whichs_which2",
		"`whichs`.`whichs_which3`" => "whichs_which3",
		"`whichs`.`whichs_description`" => "whichs_description",
		"`whichs`.`whichs_created`" => "whichs_created",
		"`whichs`.`whichs_updated`" => "whichs_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`whichs` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'whichs_view.php';
	$x->TableTitle = 'Whichs';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`whichs`.`whichs_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Whichs id', 'Which1 (Main Thing)', 'Which2 (Sub Thing)', 'Which3 (If Any)', 'Description', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['whichs_id', 'whichs_which1', 'whichs_which2', 'whichs_which3', 'whichs_description', 'whichs_created', 'whichs_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/whichs_templateTV.html';
	$x->SelectedTemplate = 'templates/whichs_templateTVS.html';
	$x->TemplateDV = 'templates/whichs_templateDV.html';
	$x->TemplateDVP = 'templates/whichs_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: whichs_init
	$render = true;
	if(function_exists('whichs_init')) {
		$args = [];
		$render = whichs_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: whichs_header
	$headerCode = '';
	if(function_exists('whichs_header')) {
		$args = [];
		$headerCode = whichs_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: whichs_footer
	$footerCode = '';
	if(function_exists('whichs_footer')) {
		$args = [];
		$footerCode = whichs_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
