<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/whos.php');
	include_once(__DIR__ . '/whos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('whos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'whos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`whos`.`whos_id`" => "whos_id",
		"`whos`.`whos_who1`" => "whos_who1",
		"`whos`.`whos_who2`" => "whos_who2",
		"`whos`.`whos_who3`" => "whos_who3",
		"`whos`.`whos_description`" => "whos_description",
		"`whos`.`whos_created`" => "whos_created",
		"`whos`.`whos_updated`" => "whos_updated",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`whos`.`whos_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`whos`.`whos_created`',
		7 => '`whos`.`whos_updated`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`whos`.`whos_id`" => "whos_id",
		"`whos`.`whos_who1`" => "whos_who1",
		"`whos`.`whos_who2`" => "whos_who2",
		"`whos`.`whos_who3`" => "whos_who3",
		"`whos`.`whos_description`" => "whos_description",
		"`whos`.`whos_created`" => "whos_created",
		"`whos`.`whos_updated`" => "whos_updated",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`whos`.`whos_id`" => "Whos id",
		"`whos`.`whos_who1`" => "Who1 (Doer Role)",
		"`whos`.`whos_who2`" => "Who2 (Doer ID)",
		"`whos`.`whos_who3`" => "Who3 (Buddy)",
		"`whos`.`whos_description`" => "Description",
		"`whos`.`whos_created`" => "Created AT",
		"`whos`.`whos_updated`" => "Updated AT",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`whos`.`whos_id`" => "whos_id",
		"`whos`.`whos_who1`" => "whos_who1",
		"`whos`.`whos_who2`" => "whos_who2",
		"`whos`.`whos_who3`" => "whos_who3",
		"`whos`.`whos_description`" => "whos_description",
		"`whos`.`whos_created`" => "whos_created",
		"`whos`.`whos_updated`" => "whos_updated",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`whos` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'whos_view.php';
	$x->TableTitle = 'Whos';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`whos`.`whos_id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Whos id', 'Who1 (Doer Role)', 'Who2 (Doer ID)', 'Who3 (Buddy)', 'Description', 'Created AT', 'Updated AT', ];
	$x->ColFieldName = ['whos_id', 'whos_who1', 'whos_who2', 'whos_who3', 'whos_description', 'whos_created', 'whos_updated', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/whos_templateTV.html';
	$x->SelectedTemplate = 'templates/whos_templateTVS.html';
	$x->TemplateDV = 'templates/whos_templateDV.html';
	$x->TemplateDVP = 'templates/whos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: whos_init
	$render = true;
	if(function_exists('whos_init')) {
		$args = [];
		$render = whos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: whos_header
	$headerCode = '';
	if(function_exists('whos_header')) {
		$args = [];
		$headerCode = whos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: whos_footer
	$footerCode = '';
	if(function_exists('whos_footer')) {
		$args = [];
		$footerCode = whos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
